load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "drkey.connect.go",
        "path.connect.go",
        "trust.connect.go",
        "underlay.connect.go",
    ],
    importpath = "github.com/scionproto/scion/pkg/proto/endhost/v1/endhostconnect",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/proto/endhost:go_default_library",
        "@com_connectrpc_connect//:go_default_library",
    ],
)
