// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/endhost/v1/path.proto

package endhostconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	endhost "github.com/scionproto/scion/pkg/proto/endhost"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SegmentsServiceName is the fully-qualified name of the SegmentsService service.
	SegmentsServiceName = "scion.endhost.v1.SegmentsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SegmentsServiceListSegmentsProcedure is the fully-qualified name of the SegmentsService's
	// ListSegments RPC.
	SegmentsServiceListSegmentsProcedure = "/scion.endhost.v1.SegmentsService/ListSegments"
)

// SegmentsServiceClient is a client for the scion.endhost.v1.SegmentsService service.
type SegmentsServiceClient interface {
	ListSegments(context.Context, *connect.Request[endhost.ListSegmentsRequest]) (*connect.Response[endhost.ListSegmentsResponse], error)
}

// NewSegmentsServiceClient constructs a client for the scion.endhost.v1.SegmentsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSegmentsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SegmentsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	segmentsServiceMethods := endhost.File_proto_endhost_v1_path_proto.Services().ByName("SegmentsService").Methods()
	return &segmentsServiceClient{
		listSegments: connect.NewClient[endhost.ListSegmentsRequest, endhost.ListSegmentsResponse](
			httpClient,
			baseURL+SegmentsServiceListSegmentsProcedure,
			connect.WithSchema(segmentsServiceMethods.ByName("ListSegments")),
			connect.WithClientOptions(opts...),
		),
	}
}

// segmentsServiceClient implements SegmentsServiceClient.
type segmentsServiceClient struct {
	listSegments *connect.Client[endhost.ListSegmentsRequest, endhost.ListSegmentsResponse]
}

// ListSegments calls scion.endhost.v1.SegmentsService.ListSegments.
func (c *segmentsServiceClient) ListSegments(ctx context.Context, req *connect.Request[endhost.ListSegmentsRequest]) (*connect.Response[endhost.ListSegmentsResponse], error) {
	return c.listSegments.CallUnary(ctx, req)
}

// SegmentsServiceHandler is an implementation of the scion.endhost.v1.SegmentsService service.
type SegmentsServiceHandler interface {
	ListSegments(context.Context, *connect.Request[endhost.ListSegmentsRequest]) (*connect.Response[endhost.ListSegmentsResponse], error)
}

// NewSegmentsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSegmentsServiceHandler(svc SegmentsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	segmentsServiceMethods := endhost.File_proto_endhost_v1_path_proto.Services().ByName("SegmentsService").Methods()
	segmentsServiceListSegmentsHandler := connect.NewUnaryHandler(
		SegmentsServiceListSegmentsProcedure,
		svc.ListSegments,
		connect.WithSchema(segmentsServiceMethods.ByName("ListSegments")),
		connect.WithHandlerOptions(opts...),
	)
	return "/scion.endhost.v1.SegmentsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SegmentsServiceListSegmentsProcedure:
			segmentsServiceListSegmentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSegmentsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSegmentsServiceHandler struct{}

func (UnimplementedSegmentsServiceHandler) ListSegments(context.Context, *connect.Request[endhost.ListSegmentsRequest]) (*connect.Response[endhost.ListSegmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scion.endhost.v1.SegmentsService.ListSegments is not implemented"))
}
