// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/endhost/v1/drkey.proto

package endhost

import (
	context "context"
	drkey "github.com/scionproto/scion/pkg/proto/drkey"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DRKeyHostASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValTime       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val_time,json=valTime,proto3" json:"val_time,omitempty"`
	ProtocolId    drkey.Protocol         `protobuf:"varint,2,opt,name=protocol_id,json=protocolId,proto3,enum=proto.drkey.v1.Protocol" json:"protocol_id,omitempty"`
	SrcIa         uint64                 `protobuf:"varint,3,opt,name=src_ia,json=srcIa,proto3" json:"src_ia,omitempty"`
	DstIa         uint64                 `protobuf:"varint,4,opt,name=dst_ia,json=dstIa,proto3" json:"dst_ia,omitempty"`
	SrcHost       string                 `protobuf:"bytes,5,opt,name=src_host,json=srcHost,proto3" json:"src_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DRKeyHostASRequest) Reset() {
	*x = DRKeyHostASRequest{}
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRKeyHostASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyHostASRequest) ProtoMessage() {}

func (x *DRKeyHostASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyHostASRequest.ProtoReflect.Descriptor instead.
func (*DRKeyHostASRequest) Descriptor() ([]byte, []int) {
	return file_proto_endhost_v1_drkey_proto_rawDescGZIP(), []int{0}
}

func (x *DRKeyHostASRequest) GetValTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValTime
	}
	return nil
}

func (x *DRKeyHostASRequest) GetProtocolId() drkey.Protocol {
	if x != nil {
		return x.ProtocolId
	}
	return drkey.Protocol(0)
}

func (x *DRKeyHostASRequest) GetSrcIa() uint64 {
	if x != nil {
		return x.SrcIa
	}
	return 0
}

func (x *DRKeyHostASRequest) GetDstIa() uint64 {
	if x != nil {
		return x.DstIa
	}
	return 0
}

func (x *DRKeyHostASRequest) GetSrcHost() string {
	if x != nil {
		return x.SrcHost
	}
	return ""
}

type DRKeyHostASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpochBegin    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=epoch_begin,json=epochBegin,proto3" json:"epoch_begin,omitempty"`
	EpochEnd      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=epoch_end,json=epochEnd,proto3" json:"epoch_end,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DRKeyHostASResponse) Reset() {
	*x = DRKeyHostASResponse{}
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRKeyHostASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyHostASResponse) ProtoMessage() {}

func (x *DRKeyHostASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyHostASResponse.ProtoReflect.Descriptor instead.
func (*DRKeyHostASResponse) Descriptor() ([]byte, []int) {
	return file_proto_endhost_v1_drkey_proto_rawDescGZIP(), []int{1}
}

func (x *DRKeyHostASResponse) GetEpochBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochBegin
	}
	return nil
}

func (x *DRKeyHostASResponse) GetEpochEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochEnd
	}
	return nil
}

func (x *DRKeyHostASResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DRKeyASHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValTime       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val_time,json=valTime,proto3" json:"val_time,omitempty"`
	ProtocolId    drkey.Protocol         `protobuf:"varint,2,opt,name=protocol_id,json=protocolId,proto3,enum=proto.drkey.v1.Protocol" json:"protocol_id,omitempty"`
	SrcIa         uint64                 `protobuf:"varint,3,opt,name=src_ia,json=srcIa,proto3" json:"src_ia,omitempty"`
	DstIa         uint64                 `protobuf:"varint,4,opt,name=dst_ia,json=dstIa,proto3" json:"dst_ia,omitempty"`
	DstHost       string                 `protobuf:"bytes,5,opt,name=dst_host,json=dstHost,proto3" json:"dst_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DRKeyASHostRequest) Reset() {
	*x = DRKeyASHostRequest{}
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRKeyASHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyASHostRequest) ProtoMessage() {}

func (x *DRKeyASHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyASHostRequest.ProtoReflect.Descriptor instead.
func (*DRKeyASHostRequest) Descriptor() ([]byte, []int) {
	return file_proto_endhost_v1_drkey_proto_rawDescGZIP(), []int{2}
}

func (x *DRKeyASHostRequest) GetValTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValTime
	}
	return nil
}

func (x *DRKeyASHostRequest) GetProtocolId() drkey.Protocol {
	if x != nil {
		return x.ProtocolId
	}
	return drkey.Protocol(0)
}

func (x *DRKeyASHostRequest) GetSrcIa() uint64 {
	if x != nil {
		return x.SrcIa
	}
	return 0
}

func (x *DRKeyASHostRequest) GetDstIa() uint64 {
	if x != nil {
		return x.DstIa
	}
	return 0
}

func (x *DRKeyASHostRequest) GetDstHost() string {
	if x != nil {
		return x.DstHost
	}
	return ""
}

type DRKeyASHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpochBegin    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=epoch_begin,json=epochBegin,proto3" json:"epoch_begin,omitempty"`
	EpochEnd      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=epoch_end,json=epochEnd,proto3" json:"epoch_end,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DRKeyASHostResponse) Reset() {
	*x = DRKeyASHostResponse{}
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRKeyASHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyASHostResponse) ProtoMessage() {}

func (x *DRKeyASHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyASHostResponse.ProtoReflect.Descriptor instead.
func (*DRKeyASHostResponse) Descriptor() ([]byte, []int) {
	return file_proto_endhost_v1_drkey_proto_rawDescGZIP(), []int{3}
}

func (x *DRKeyASHostResponse) GetEpochBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochBegin
	}
	return nil
}

func (x *DRKeyASHostResponse) GetEpochEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochEnd
	}
	return nil
}

func (x *DRKeyASHostResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DRKeyHostHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValTime       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val_time,json=valTime,proto3" json:"val_time,omitempty"`
	ProtocolId    drkey.Protocol         `protobuf:"varint,2,opt,name=protocol_id,json=protocolId,proto3,enum=proto.drkey.v1.Protocol" json:"protocol_id,omitempty"`
	SrcIa         uint64                 `protobuf:"varint,3,opt,name=src_ia,json=srcIa,proto3" json:"src_ia,omitempty"`
	DstIa         uint64                 `protobuf:"varint,4,opt,name=dst_ia,json=dstIa,proto3" json:"dst_ia,omitempty"`
	SrcHost       string                 `protobuf:"bytes,5,opt,name=src_host,json=srcHost,proto3" json:"src_host,omitempty"`
	DstHost       string                 `protobuf:"bytes,6,opt,name=dst_host,json=dstHost,proto3" json:"dst_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DRKeyHostHostRequest) Reset() {
	*x = DRKeyHostHostRequest{}
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRKeyHostHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyHostHostRequest) ProtoMessage() {}

func (x *DRKeyHostHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyHostHostRequest.ProtoReflect.Descriptor instead.
func (*DRKeyHostHostRequest) Descriptor() ([]byte, []int) {
	return file_proto_endhost_v1_drkey_proto_rawDescGZIP(), []int{4}
}

func (x *DRKeyHostHostRequest) GetValTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValTime
	}
	return nil
}

func (x *DRKeyHostHostRequest) GetProtocolId() drkey.Protocol {
	if x != nil {
		return x.ProtocolId
	}
	return drkey.Protocol(0)
}

func (x *DRKeyHostHostRequest) GetSrcIa() uint64 {
	if x != nil {
		return x.SrcIa
	}
	return 0
}

func (x *DRKeyHostHostRequest) GetDstIa() uint64 {
	if x != nil {
		return x.DstIa
	}
	return 0
}

func (x *DRKeyHostHostRequest) GetSrcHost() string {
	if x != nil {
		return x.SrcHost
	}
	return ""
}

func (x *DRKeyHostHostRequest) GetDstHost() string {
	if x != nil {
		return x.DstHost
	}
	return ""
}

type DRKeyHostHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpochBegin    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=epoch_begin,json=epochBegin,proto3" json:"epoch_begin,omitempty"`
	EpochEnd      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=epoch_end,json=epochEnd,proto3" json:"epoch_end,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DRKeyHostHostResponse) Reset() {
	*x = DRKeyHostHostResponse{}
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRKeyHostHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyHostHostResponse) ProtoMessage() {}

func (x *DRKeyHostHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_endhost_v1_drkey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyHostHostResponse.ProtoReflect.Descriptor instead.
func (*DRKeyHostHostResponse) Descriptor() ([]byte, []int) {
	return file_proto_endhost_v1_drkey_proto_rawDescGZIP(), []int{5}
}

func (x *DRKeyHostHostResponse) GetEpochBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochBegin
	}
	return nil
}

func (x *DRKeyHostHostResponse) GetEpochEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochEnd
	}
	return nil
}

func (x *DRKeyHostHostResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_proto_endhost_v1_drkey_proto protoreflect.FileDescriptor

const file_proto_endhost_v1_drkey_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/endhost/v1/drkey.proto\x12\x10scion.endhost.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aproto/drkey/v1/drkey.proto\"\xcf\x01\n" +
	"\x12DRKeyHostASRequest\x125\n" +
	"\bval_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\avalTime\x129\n" +
	"\vprotocol_id\x18\x02 \x01(\x0e2\x18.proto.drkey.v1.ProtocolR\n" +
	"protocolId\x12\x15\n" +
	"\x06src_ia\x18\x03 \x01(\x04R\x05srcIa\x12\x15\n" +
	"\x06dst_ia\x18\x04 \x01(\x04R\x05dstIa\x12\x19\n" +
	"\bsrc_host\x18\x05 \x01(\tR\asrcHost\"\x9d\x01\n" +
	"\x13DRKeyHostASResponse\x12;\n" +
	"\vepoch_begin\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"epochBegin\x127\n" +
	"\tepoch_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bepochEnd\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\"\xcf\x01\n" +
	"\x12DRKeyASHostRequest\x125\n" +
	"\bval_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\avalTime\x129\n" +
	"\vprotocol_id\x18\x02 \x01(\x0e2\x18.proto.drkey.v1.ProtocolR\n" +
	"protocolId\x12\x15\n" +
	"\x06src_ia\x18\x03 \x01(\x04R\x05srcIa\x12\x15\n" +
	"\x06dst_ia\x18\x04 \x01(\x04R\x05dstIa\x12\x19\n" +
	"\bdst_host\x18\x05 \x01(\tR\adstHost\"\x9d\x01\n" +
	"\x13DRKeyASHostResponse\x12;\n" +
	"\vepoch_begin\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"epochBegin\x127\n" +
	"\tepoch_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bepochEnd\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\"\xec\x01\n" +
	"\x14DRKeyHostHostRequest\x125\n" +
	"\bval_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\avalTime\x129\n" +
	"\vprotocol_id\x18\x02 \x01(\x0e2\x18.proto.drkey.v1.ProtocolR\n" +
	"protocolId\x12\x15\n" +
	"\x06src_ia\x18\x03 \x01(\x04R\x05srcIa\x12\x15\n" +
	"\x06dst_ia\x18\x04 \x01(\x04R\x05dstIa\x12\x19\n" +
	"\bsrc_host\x18\x05 \x01(\tR\asrcHost\x12\x19\n" +
	"\bdst_host\x18\x06 \x01(\tR\adstHost\"\x9f\x01\n" +
	"\x15DRKeyHostHostResponse\x12;\n" +
	"\vepoch_begin\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"epochBegin\x127\n" +
	"\tepoch_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bepochEnd\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key2\xae\x02\n" +
	"\fDRKeyService\x12\\\n" +
	"\vDRKeyASHost\x12$.scion.endhost.v1.DRKeyASHostRequest\x1a%.scion.endhost.v1.DRKeyASHostResponse\"\x00\x12\\\n" +
	"\vDRKeyHostAS\x12$.scion.endhost.v1.DRKeyHostASRequest\x1a%.scion.endhost.v1.DRKeyHostASResponse\"\x00\x12b\n" +
	"\rDRKeyHostHost\x12&.scion.endhost.v1.DRKeyHostHostRequest\x1a'.scion.endhost.v1.DRKeyHostHostResponse\"\x00B/Z-github.com/scionproto/scion/pkg/proto/endhostb\x06proto3"

var (
	file_proto_endhost_v1_drkey_proto_rawDescOnce sync.Once
	file_proto_endhost_v1_drkey_proto_rawDescData []byte
)

func file_proto_endhost_v1_drkey_proto_rawDescGZIP() []byte {
	file_proto_endhost_v1_drkey_proto_rawDescOnce.Do(func() {
		file_proto_endhost_v1_drkey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_endhost_v1_drkey_proto_rawDesc), len(file_proto_endhost_v1_drkey_proto_rawDesc)))
	})
	return file_proto_endhost_v1_drkey_proto_rawDescData
}

var file_proto_endhost_v1_drkey_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_endhost_v1_drkey_proto_goTypes = []any{
	(*DRKeyHostASRequest)(nil),    // 0: scion.endhost.v1.DRKeyHostASRequest
	(*DRKeyHostASResponse)(nil),   // 1: scion.endhost.v1.DRKeyHostASResponse
	(*DRKeyASHostRequest)(nil),    // 2: scion.endhost.v1.DRKeyASHostRequest
	(*DRKeyASHostResponse)(nil),   // 3: scion.endhost.v1.DRKeyASHostResponse
	(*DRKeyHostHostRequest)(nil),  // 4: scion.endhost.v1.DRKeyHostHostRequest
	(*DRKeyHostHostResponse)(nil), // 5: scion.endhost.v1.DRKeyHostHostResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(drkey.Protocol)(0),           // 7: proto.drkey.v1.Protocol
}
var file_proto_endhost_v1_drkey_proto_depIdxs = []int32{
	6,  // 0: scion.endhost.v1.DRKeyHostASRequest.val_time:type_name -> google.protobuf.Timestamp
	7,  // 1: scion.endhost.v1.DRKeyHostASRequest.protocol_id:type_name -> proto.drkey.v1.Protocol
	6,  // 2: scion.endhost.v1.DRKeyHostASResponse.epoch_begin:type_name -> google.protobuf.Timestamp
	6,  // 3: scion.endhost.v1.DRKeyHostASResponse.epoch_end:type_name -> google.protobuf.Timestamp
	6,  // 4: scion.endhost.v1.DRKeyASHostRequest.val_time:type_name -> google.protobuf.Timestamp
	7,  // 5: scion.endhost.v1.DRKeyASHostRequest.protocol_id:type_name -> proto.drkey.v1.Protocol
	6,  // 6: scion.endhost.v1.DRKeyASHostResponse.epoch_begin:type_name -> google.protobuf.Timestamp
	6,  // 7: scion.endhost.v1.DRKeyASHostResponse.epoch_end:type_name -> google.protobuf.Timestamp
	6,  // 8: scion.endhost.v1.DRKeyHostHostRequest.val_time:type_name -> google.protobuf.Timestamp
	7,  // 9: scion.endhost.v1.DRKeyHostHostRequest.protocol_id:type_name -> proto.drkey.v1.Protocol
	6,  // 10: scion.endhost.v1.DRKeyHostHostResponse.epoch_begin:type_name -> google.protobuf.Timestamp
	6,  // 11: scion.endhost.v1.DRKeyHostHostResponse.epoch_end:type_name -> google.protobuf.Timestamp
	2,  // 12: scion.endhost.v1.DRKeyService.DRKeyASHost:input_type -> scion.endhost.v1.DRKeyASHostRequest
	0,  // 13: scion.endhost.v1.DRKeyService.DRKeyHostAS:input_type -> scion.endhost.v1.DRKeyHostASRequest
	4,  // 14: scion.endhost.v1.DRKeyService.DRKeyHostHost:input_type -> scion.endhost.v1.DRKeyHostHostRequest
	3,  // 15: scion.endhost.v1.DRKeyService.DRKeyASHost:output_type -> scion.endhost.v1.DRKeyASHostResponse
	1,  // 16: scion.endhost.v1.DRKeyService.DRKeyHostAS:output_type -> scion.endhost.v1.DRKeyHostASResponse
	5,  // 17: scion.endhost.v1.DRKeyService.DRKeyHostHost:output_type -> scion.endhost.v1.DRKeyHostHostResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_endhost_v1_drkey_proto_init() }
func file_proto_endhost_v1_drkey_proto_init() {
	if File_proto_endhost_v1_drkey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_endhost_v1_drkey_proto_rawDesc), len(file_proto_endhost_v1_drkey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_endhost_v1_drkey_proto_goTypes,
		DependencyIndexes: file_proto_endhost_v1_drkey_proto_depIdxs,
		MessageInfos:      file_proto_endhost_v1_drkey_proto_msgTypes,
	}.Build()
	File_proto_endhost_v1_drkey_proto = out.File
	file_proto_endhost_v1_drkey_proto_goTypes = nil
	file_proto_endhost_v1_drkey_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DRKeyServiceClient is the client API for DRKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DRKeyServiceClient interface {
	DRKeyASHost(ctx context.Context, in *DRKeyASHostRequest, opts ...grpc.CallOption) (*DRKeyASHostResponse, error)
	DRKeyHostAS(ctx context.Context, in *DRKeyHostASRequest, opts ...grpc.CallOption) (*DRKeyHostASResponse, error)
	DRKeyHostHost(ctx context.Context, in *DRKeyHostHostRequest, opts ...grpc.CallOption) (*DRKeyHostHostResponse, error)
}

type dRKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDRKeyServiceClient(cc grpc.ClientConnInterface) DRKeyServiceClient {
	return &dRKeyServiceClient{cc}
}

func (c *dRKeyServiceClient) DRKeyASHost(ctx context.Context, in *DRKeyASHostRequest, opts ...grpc.CallOption) (*DRKeyASHostResponse, error) {
	out := new(DRKeyASHostResponse)
	err := c.cc.Invoke(ctx, "/scion.endhost.v1.DRKeyService/DRKeyASHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dRKeyServiceClient) DRKeyHostAS(ctx context.Context, in *DRKeyHostASRequest, opts ...grpc.CallOption) (*DRKeyHostASResponse, error) {
	out := new(DRKeyHostASResponse)
	err := c.cc.Invoke(ctx, "/scion.endhost.v1.DRKeyService/DRKeyHostAS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dRKeyServiceClient) DRKeyHostHost(ctx context.Context, in *DRKeyHostHostRequest, opts ...grpc.CallOption) (*DRKeyHostHostResponse, error) {
	out := new(DRKeyHostHostResponse)
	err := c.cc.Invoke(ctx, "/scion.endhost.v1.DRKeyService/DRKeyHostHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DRKeyServiceServer is the server API for DRKeyService service.
type DRKeyServiceServer interface {
	DRKeyASHost(context.Context, *DRKeyASHostRequest) (*DRKeyASHostResponse, error)
	DRKeyHostAS(context.Context, *DRKeyHostASRequest) (*DRKeyHostASResponse, error)
	DRKeyHostHost(context.Context, *DRKeyHostHostRequest) (*DRKeyHostHostResponse, error)
}

// UnimplementedDRKeyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDRKeyServiceServer struct {
}

func (*UnimplementedDRKeyServiceServer) DRKeyASHost(context.Context, *DRKeyASHostRequest) (*DRKeyASHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DRKeyASHost not implemented")
}
func (*UnimplementedDRKeyServiceServer) DRKeyHostAS(context.Context, *DRKeyHostASRequest) (*DRKeyHostASResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DRKeyHostAS not implemented")
}
func (*UnimplementedDRKeyServiceServer) DRKeyHostHost(context.Context, *DRKeyHostHostRequest) (*DRKeyHostHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DRKeyHostHost not implemented")
}

func RegisterDRKeyServiceServer(s *grpc.Server, srv DRKeyServiceServer) {
	s.RegisterService(&_DRKeyService_serviceDesc, srv)
}

func _DRKeyService_DRKeyASHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DRKeyASHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRKeyServiceServer).DRKeyASHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scion.endhost.v1.DRKeyService/DRKeyASHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRKeyServiceServer).DRKeyASHost(ctx, req.(*DRKeyASHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DRKeyService_DRKeyHostAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DRKeyHostASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRKeyServiceServer).DRKeyHostAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scion.endhost.v1.DRKeyService/DRKeyHostAS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRKeyServiceServer).DRKeyHostAS(ctx, req.(*DRKeyHostASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DRKeyService_DRKeyHostHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DRKeyHostHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRKeyServiceServer).DRKeyHostHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scion.endhost.v1.DRKeyService/DRKeyHostHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRKeyServiceServer).DRKeyHostHost(ctx, req.(*DRKeyHostHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DRKeyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scion.endhost.v1.DRKeyService",
	HandlerType: (*DRKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DRKeyASHost",
			Handler:    _DRKeyService_DRKeyASHost_Handler,
		},
		{
			MethodName: "DRKeyHostAS",
			Handler:    _DRKeyService_DRKeyHostAS_Handler,
		},
		{
			MethodName: "DRKeyHostHost",
			Handler:    _DRKeyService_DRKeyHostHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/endhost/v1/drkey.proto",
}
