// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.1
// source: proto/hummingbird/v1/marketplace.proto

package hummingbird

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PricingStrategy int32

const (
	PricingStrategy_static_pricing  PricingStrategy = 0
	PricingStrategy_dynamic_pricing PricingStrategy = 1
)

// Enum value maps for PricingStrategy.
var (
	PricingStrategy_name = map[int32]string{
		0: "static_pricing",
		1: "dynamic_pricing",
	}
	PricingStrategy_value = map[string]int32{
		"static_pricing":  0,
		"dynamic_pricing": 1,
	}
)

func (x PricingStrategy) Enum() *PricingStrategy {
	p := new(PricingStrategy)
	*p = x
	return p
}

func (x PricingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PricingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hummingbird_v1_marketplace_proto_enumTypes[0].Descriptor()
}

func (PricingStrategy) Type() protoreflect.EnumType {
	return &file_proto_hummingbird_v1_marketplace_proto_enumTypes[0]
}

func (x PricingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PricingStrategy.Descriptor instead.
func (PricingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{0}
}

type UpdateAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*AssetUpdate         `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetsRequest) Reset() {
	*x = UpdateAssetsRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetsRequest) ProtoMessage() {}

func (x *UpdateAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateAssetsRequest) GetAssets() []*AssetUpdate {
	if x != nil {
		return x.Assets
	}
	return nil
}

type AssetUpdate struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AssetId []byte                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*AssetUpdate_Update
	//	*AssetUpdate_Remove
	Operation     isAssetUpdate_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetUpdate) Reset() {
	*x = AssetUpdate{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetUpdate) ProtoMessage() {}

func (x *AssetUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetUpdate.ProtoReflect.Descriptor instead.
func (*AssetUpdate) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{1}
}

func (x *AssetUpdate) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

func (x *AssetUpdate) GetOperation() isAssetUpdate_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *AssetUpdate) GetUpdate() *PublisherAsset {
	if x != nil {
		if x, ok := x.Operation.(*AssetUpdate_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *AssetUpdate) GetRemove() *Remove {
	if x != nil {
		if x, ok := x.Operation.(*AssetUpdate_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

type isAssetUpdate_Operation interface {
	isAssetUpdate_Operation()
}

type AssetUpdate_Update struct {
	Update *PublisherAsset `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type AssetUpdate_Remove struct {
	Remove *Remove `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*AssetUpdate_Update) isAssetUpdate_Operation() {}

func (*AssetUpdate_Remove) isAssetUpdate_Operation() {}

type Remove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Remove) Reset() {
	*x = Remove{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remove) ProtoMessage() {}

func (x *Remove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remove.ProtoReflect.Descriptor instead.
func (*Remove) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{2}
}

type UpdateAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*UpdateAssetResult   `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetsResponse) Reset() {
	*x = UpdateAssetsResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetsResponse) ProtoMessage() {}

func (x *UpdateAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetsResponse.ProtoReflect.Descriptor instead.
func (*UpdateAssetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAssetsResponse) GetResult() []*UpdateAssetResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdateAssetResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResultType:
	//
	//	*UpdateAssetResult_NewId
	//	*UpdateAssetResult_Error
	ResultType    isUpdateAssetResult_ResultType `protobuf_oneof:"result_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetResult) Reset() {
	*x = UpdateAssetResult{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetResult) ProtoMessage() {}

func (x *UpdateAssetResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetResult.ProtoReflect.Descriptor instead.
func (*UpdateAssetResult) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAssetResult) GetResultType() isUpdateAssetResult_ResultType {
	if x != nil {
		return x.ResultType
	}
	return nil
}

func (x *UpdateAssetResult) GetNewId() []byte {
	if x != nil {
		if x, ok := x.ResultType.(*UpdateAssetResult_NewId); ok {
			return x.NewId
		}
	}
	return nil
}

func (x *UpdateAssetResult) GetError() string {
	if x != nil {
		if x, ok := x.ResultType.(*UpdateAssetResult_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isUpdateAssetResult_ResultType interface {
	isUpdateAssetResult_ResultType()
}

type UpdateAssetResult_NewId struct {
	NewId []byte `protobuf:"bytes,1,opt,name=new_id,json=newId,proto3,oneof"`
}

type UpdateAssetResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UpdateAssetResult_NewId) isUpdateAssetResult_ResultType() {}

func (*UpdateAssetResult_Error) isUpdateAssetResult_ResultType() {}

type StatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IfIdIngress   *uint32                `protobuf:"varint,1,opt,name=if_id_ingress,json=ifIdIngress,proto3,oneof" json:"if_id_ingress,omitempty"`
	IfIdEgress    *uint32                `protobuf:"varint,2,opt,name=if_id_egress,json=ifIdEgress,proto3,oneof" json:"if_id_egress,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Step          uint32                 `protobuf:"varint,5,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsRequest) Reset() {
	*x = StatisticsRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsRequest) ProtoMessage() {}

func (x *StatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsRequest.ProtoReflect.Descriptor instead.
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{5}
}

func (x *StatisticsRequest) GetIfIdIngress() uint32 {
	if x != nil && x.IfIdIngress != nil {
		return *x.IfIdIngress
	}
	return 0
}

func (x *StatisticsRequest) GetIfIdEgress() uint32 {
	if x != nil && x.IfIdEgress != nil {
		return *x.IfIdEgress
	}
	return 0
}

func (x *StatisticsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *StatisticsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *StatisticsRequest) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type StatisticsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Statistics    []*StatisticsResponseEntry `protobuf:"bytes,1,rep,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse.ProtoReflect.Descriptor instead.
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{6}
}

func (x *StatisticsResponse) GetStatistics() []*StatisticsResponseEntry {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type StatisticsResponseEntry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Revenue              uint64                 `protobuf:"varint,1,opt,name=revenue,proto3" json:"revenue,omitempty"`
	BandwidthUtilization float64                `protobuf:"fixed64,2,opt,name=bandwidth_utilization,json=bandwidthUtilization,proto3" json:"bandwidth_utilization,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatisticsResponseEntry) Reset() {
	*x = StatisticsResponseEntry{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponseEntry) ProtoMessage() {}

func (x *StatisticsResponseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponseEntry.ProtoReflect.Descriptor instead.
func (*StatisticsResponseEntry) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{7}
}

func (x *StatisticsResponseEntry) GetRevenue() uint64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *StatisticsResponseEntry) GetBandwidthUtilization() float64 {
	if x != nil {
		return x.BandwidthUtilization
	}
	return 0
}

type SplitAssetRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AssetId []byte                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Types that are valid to be assigned to SplitOption:
	//
	//	*SplitAssetRequest_BwSplit
	//	*SplitAssetRequest_TimeSplit
	SplitOption   isSplitAssetRequest_SplitOption `protobuf_oneof:"split_option"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitAssetRequest) Reset() {
	*x = SplitAssetRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitAssetRequest) ProtoMessage() {}

func (x *SplitAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitAssetRequest.ProtoReflect.Descriptor instead.
func (*SplitAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{8}
}

func (x *SplitAssetRequest) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

func (x *SplitAssetRequest) GetSplitOption() isSplitAssetRequest_SplitOption {
	if x != nil {
		return x.SplitOption
	}
	return nil
}

func (x *SplitAssetRequest) GetBwSplit() *SplitBwOption {
	if x != nil {
		if x, ok := x.SplitOption.(*SplitAssetRequest_BwSplit); ok {
			return x.BwSplit
		}
	}
	return nil
}

func (x *SplitAssetRequest) GetTimeSplit() *SplitTimeOption {
	if x != nil {
		if x, ok := x.SplitOption.(*SplitAssetRequest_TimeSplit); ok {
			return x.TimeSplit
		}
	}
	return nil
}

type isSplitAssetRequest_SplitOption interface {
	isSplitAssetRequest_SplitOption()
}

type SplitAssetRequest_BwSplit struct {
	BwSplit *SplitBwOption `protobuf:"bytes,2,opt,name=bw_split,json=bwSplit,proto3,oneof"`
}

type SplitAssetRequest_TimeSplit struct {
	TimeSplit *SplitTimeOption `protobuf:"bytes,3,opt,name=time_split,json=timeSplit,proto3,oneof"`
}

func (*SplitAssetRequest_BwSplit) isSplitAssetRequest_SplitOption() {}

func (*SplitAssetRequest_TimeSplit) isSplitAssetRequest_SplitOption() {}

type SplitBwOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Splits        []uint32               `protobuf:"varint,1,rep,packed,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitBwOption) Reset() {
	*x = SplitBwOption{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitBwOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitBwOption) ProtoMessage() {}

func (x *SplitBwOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitBwOption.ProtoReflect.Descriptor instead.
func (*SplitBwOption) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{9}
}

func (x *SplitBwOption) GetSplits() []uint32 {
	if x != nil {
		return x.Splits
	}
	return nil
}

type SplitTimeOption struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Splits        []*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitTimeOption) Reset() {
	*x = SplitTimeOption{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitTimeOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitTimeOption) ProtoMessage() {}

func (x *SplitTimeOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitTimeOption.ProtoReflect.Descriptor instead.
func (*SplitTimeOption) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{10}
}

func (x *SplitTimeOption) GetSplits() []*timestamppb.Timestamp {
	if x != nil {
		return x.Splits
	}
	return nil
}

type SplitAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetIds      [][]byte               `protobuf:"bytes,1,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitAssetResponse) Reset() {
	*x = SplitAssetResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitAssetResponse) ProtoMessage() {}

func (x *SplitAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitAssetResponse.ProtoReflect.Descriptor instead.
func (*SplitAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{11}
}

func (x *SplitAssetResponse) GetAssetIds() [][]byte {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type CombineAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetIds      [][]byte               `protobuf:"bytes,1,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombineAssetRequest) Reset() {
	*x = CombineAssetRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombineAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombineAssetRequest) ProtoMessage() {}

func (x *CombineAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombineAssetRequest.ProtoReflect.Descriptor instead.
func (*CombineAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{12}
}

func (x *CombineAssetRequest) GetAssetIds() [][]byte {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type CombineAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       []byte                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombineAssetResponse) Reset() {
	*x = CombineAssetResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombineAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombineAssetResponse) ProtoMessage() {}

func (x *CombineAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombineAssetResponse.ProtoReflect.Descriptor instead.
func (*CombineAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{13}
}

func (x *CombineAssetResponse) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

type MarketplaceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceInfoRequest) Reset() {
	*x = MarketplaceInfoRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceInfoRequest) ProtoMessage() {}

func (x *MarketplaceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceInfoRequest.ProtoReflect.Descriptor instead.
func (*MarketplaceInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{14}
}

type MarketplaceInfoResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ApiMajorVersion              uint32                 `protobuf:"varint,1,opt,name=api_major_version,json=apiMajorVersion,proto3" json:"api_major_version,omitempty"`
	ApiMinorVersion              uint32                 `protobuf:"varint,2,opt,name=api_minor_version,json=apiMinorVersion,proto3" json:"api_minor_version,omitempty"`
	Currency                     string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencyExponent             uint32                 `protobuf:"varint,4,opt,name=currency_exponent,json=currencyExponent,proto3" json:"currency_exponent,omitempty"`
	MaxStatisticsGranularity     uint32                 `protobuf:"varint,5,opt,name=max_statistics_granularity,json=maxStatisticsGranularity,proto3" json:"max_statistics_granularity,omitempty"`
	PricingStrategy              PricingStrategy        `protobuf:"varint,6,opt,name=pricing_strategy,json=pricingStrategy,proto3,enum=proto.hummingbird.v1.PricingStrategy" json:"pricing_strategy,omitempty"`
	TransactionFeeRelative       float32                `protobuf:"fixed32,7,opt,name=transaction_fee_relative,json=transactionFeeRelative,proto3" json:"transaction_fee_relative,omitempty"`
	TransactionFeeAbsolute       uint64                 `protobuf:"varint,8,opt,name=transaction_fee_absolute,json=transactionFeeAbsolute,proto3" json:"transaction_fee_absolute,omitempty"`
	SplitCombineFeeAbsolute      uint64                 `protobuf:"varint,9,opt,name=split_combine_fee_absolute,json=splitCombineFeeAbsolute,proto3" json:"split_combine_fee_absolute,omitempty"`
	SupportsRedemptionDelegation bool                   `protobuf:"varint,10,opt,name=supports_redemption_delegation,json=supportsRedemptionDelegation,proto3" json:"supports_redemption_delegation,omitempty"`
	DelegationHourlyFee          uint64                 `protobuf:"varint,11,opt,name=delegation_hourly_fee,json=delegationHourlyFee,proto3" json:"delegation_hourly_fee,omitempty"`
	AssetValidityMax             uint32                 `protobuf:"varint,12,opt,name=asset_validity_max,json=assetValidityMax,proto3" json:"asset_validity_max,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *MarketplaceInfoResponse) Reset() {
	*x = MarketplaceInfoResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceInfoResponse) ProtoMessage() {}

func (x *MarketplaceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceInfoResponse.ProtoReflect.Descriptor instead.
func (*MarketplaceInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{15}
}

func (x *MarketplaceInfoResponse) GetApiMajorVersion() uint32 {
	if x != nil {
		return x.ApiMajorVersion
	}
	return 0
}

func (x *MarketplaceInfoResponse) GetApiMinorVersion() uint32 {
	if x != nil {
		return x.ApiMinorVersion
	}
	return 0
}

func (x *MarketplaceInfoResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MarketplaceInfoResponse) GetCurrencyExponent() uint32 {
	if x != nil {
		return x.CurrencyExponent
	}
	return 0
}

func (x *MarketplaceInfoResponse) GetMaxStatisticsGranularity() uint32 {
	if x != nil {
		return x.MaxStatisticsGranularity
	}
	return 0
}

func (x *MarketplaceInfoResponse) GetPricingStrategy() PricingStrategy {
	if x != nil {
		return x.PricingStrategy
	}
	return PricingStrategy_static_pricing
}

func (x *MarketplaceInfoResponse) GetTransactionFeeRelative() float32 {
	if x != nil {
		return x.TransactionFeeRelative
	}
	return 0
}

func (x *MarketplaceInfoResponse) GetTransactionFeeAbsolute() uint64 {
	if x != nil {
		return x.TransactionFeeAbsolute
	}
	return 0
}

func (x *MarketplaceInfoResponse) GetSplitCombineFeeAbsolute() uint64 {
	if x != nil {
		return x.SplitCombineFeeAbsolute
	}
	return 0
}

func (x *MarketplaceInfoResponse) GetSupportsRedemptionDelegation() bool {
	if x != nil {
		return x.SupportsRedemptionDelegation
	}
	return false
}

func (x *MarketplaceInfoResponse) GetDelegationHourlyFee() uint64 {
	if x != nil {
		return x.DelegationHourlyFee
	}
	return 0
}

func (x *MarketplaceInfoResponse) GetAssetValidityMax() uint32 {
	if x != nil {
		return x.AssetValidityMax
	}
	return 0
}

type PublishAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *PublisherAsset        `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAssetRequest) Reset() {
	*x = PublishAssetRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAssetRequest) ProtoMessage() {}

func (x *PublishAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAssetRequest.ProtoReflect.Descriptor instead.
func (*PublishAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{16}
}

func (x *PublishAssetRequest) GetAsset() *PublisherAsset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type PublishAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       []byte                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAssetResponse) Reset() {
	*x = PublishAssetResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAssetResponse) ProtoMessage() {}

func (x *PublishAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAssetResponse.ProtoReflect.Descriptor instead.
func (*PublishAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{17}
}

func (x *PublishAssetResponse) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

type PublisherAsset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IfIdIngress     *uint32                `protobuf:"varint,1,opt,name=if_id_ingress,json=ifIdIngress,proto3,oneof" json:"if_id_ingress,omitempty"`
	IfIdEgress      *uint32                `protobuf:"varint,2,opt,name=if_id_egress,json=ifIdEgress,proto3,oneof" json:"if_id_egress,omitempty"`
	Bandwidth       uint32                 `protobuf:"varint,3,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	BandwidthMin    uint32                 `protobuf:"varint,4,opt,name=bandwidth_min,json=bandwidthMin,proto3" json:"bandwidth_min,omitempty"`
	BandwidthMax    uint32                 `protobuf:"varint,5,opt,name=bandwidth_max,json=bandwidthMax,proto3" json:"bandwidth_max,omitempty"`
	StartsAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	StopsAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=stops_at,json=stopsAt,proto3" json:"stops_at,omitempty"`
	TimeGranularity uint32                 `protobuf:"varint,8,opt,name=time_granularity,json=timeGranularity,proto3" json:"time_granularity,omitempty"`
	TimeMinDuration uint32                 `protobuf:"varint,9,opt,name=time_min_duration,json=timeMinDuration,proto3" json:"time_min_duration,omitempty"`
	TimeMaxDuration uint32                 `protobuf:"varint,10,opt,name=time_max_duration,json=timeMaxDuration,proto3" json:"time_max_duration,omitempty"`
	Price           uint32                 `protobuf:"varint,11,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublisherAsset) Reset() {
	*x = PublisherAsset{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherAsset) ProtoMessage() {}

func (x *PublisherAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherAsset.ProtoReflect.Descriptor instead.
func (*PublisherAsset) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{18}
}

func (x *PublisherAsset) GetIfIdIngress() uint32 {
	if x != nil && x.IfIdIngress != nil {
		return *x.IfIdIngress
	}
	return 0
}

func (x *PublisherAsset) GetIfIdEgress() uint32 {
	if x != nil && x.IfIdEgress != nil {
		return *x.IfIdEgress
	}
	return 0
}

func (x *PublisherAsset) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *PublisherAsset) GetBandwidthMin() uint32 {
	if x != nil {
		return x.BandwidthMin
	}
	return 0
}

func (x *PublisherAsset) GetBandwidthMax() uint32 {
	if x != nil {
		return x.BandwidthMax
	}
	return 0
}

func (x *PublisherAsset) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *PublisherAsset) GetStopsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StopsAt
	}
	return nil
}

func (x *PublisherAsset) GetTimeGranularity() uint32 {
	if x != nil {
		return x.TimeGranularity
	}
	return 0
}

func (x *PublisherAsset) GetTimeMinDuration() uint32 {
	if x != nil {
		return x.TimeMinDuration
	}
	return 0
}

func (x *PublisherAsset) GetTimeMaxDuration() uint32 {
	if x != nil {
		return x.TimeMaxDuration
	}
	return 0
}

func (x *PublisherAsset) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SearchAssetsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Owned             bool                   `protobuf:"varint,1,opt,name=owned,proto3" json:"owned,omitempty"`
	Ia                *uint64                `protobuf:"varint,2,opt,name=ia,proto3,oneof" json:"ia,omitempty"`
	IfIdIngress       *uint32                `protobuf:"varint,3,opt,name=if_id_ingress,json=ifIdIngress,proto3,oneof" json:"if_id_ingress,omitempty"`
	IfIdEgress        *uint32                `protobuf:"varint,4,opt,name=if_id_egress,json=ifIdEgress,proto3,oneof" json:"if_id_egress,omitempty"`
	MinRequiredBw     *uint32                `protobuf:"varint,5,opt,name=min_required_bw,json=minRequiredBw,proto3,oneof" json:"min_required_bw,omitempty"`
	StartsAtLatest    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=starts_at_latest,json=startsAtLatest,proto3,oneof" json:"starts_at_latest,omitempty"`
	StopsAtEarliest   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=stops_at_earliest,json=stopsAtEarliest,proto3,oneof" json:"stops_at_earliest,omitempty"`
	Price             *uint32                `protobuf:"varint,8,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Page              uint32                 `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	MaxReturnedAssets *uint32                `protobuf:"varint,10,opt,name=max_returned_assets,json=maxReturnedAssets,proto3,oneof" json:"max_returned_assets,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchAssetsRequest) Reset() {
	*x = SearchAssetsRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAssetsRequest) ProtoMessage() {}

func (x *SearchAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAssetsRequest.ProtoReflect.Descriptor instead.
func (*SearchAssetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{19}
}

func (x *SearchAssetsRequest) GetOwned() bool {
	if x != nil {
		return x.Owned
	}
	return false
}

func (x *SearchAssetsRequest) GetIa() uint64 {
	if x != nil && x.Ia != nil {
		return *x.Ia
	}
	return 0
}

func (x *SearchAssetsRequest) GetIfIdIngress() uint32 {
	if x != nil && x.IfIdIngress != nil {
		return *x.IfIdIngress
	}
	return 0
}

func (x *SearchAssetsRequest) GetIfIdEgress() uint32 {
	if x != nil && x.IfIdEgress != nil {
		return *x.IfIdEgress
	}
	return 0
}

func (x *SearchAssetsRequest) GetMinRequiredBw() uint32 {
	if x != nil && x.MinRequiredBw != nil {
		return *x.MinRequiredBw
	}
	return 0
}

func (x *SearchAssetsRequest) GetStartsAtLatest() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAtLatest
	}
	return nil
}

func (x *SearchAssetsRequest) GetStopsAtEarliest() *timestamppb.Timestamp {
	if x != nil {
		return x.StopsAtEarliest
	}
	return nil
}

func (x *SearchAssetsRequest) GetPrice() uint32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *SearchAssetsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchAssetsRequest) GetMaxReturnedAssets() uint32 {
	if x != nil && x.MaxReturnedAssets != nil {
		return *x.MaxReturnedAssets
	}
	return 0
}

type SearchAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*SearchAsset         `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAssetsResponse) Reset() {
	*x = SearchAssetsResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAssetsResponse) ProtoMessage() {}

func (x *SearchAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAssetsResponse.ProtoReflect.Descriptor instead.
func (*SearchAssetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{20}
}

func (x *SearchAssetsResponse) GetAssets() []*SearchAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type SearchAsset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssetId         []byte                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Ia              uint64                 `protobuf:"varint,2,opt,name=ia,proto3" json:"ia,omitempty"`
	IfIdIngress     *uint32                `protobuf:"varint,3,opt,name=if_id_ingress,json=ifIdIngress,proto3,oneof" json:"if_id_ingress,omitempty"`
	IfIdEgress      *uint32                `protobuf:"varint,4,opt,name=if_id_egress,json=ifIdEgress,proto3,oneof" json:"if_id_egress,omitempty"`
	Bandwidth       uint32                 `protobuf:"varint,5,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	BandwidthMin    uint32                 `protobuf:"varint,6,opt,name=bandwidth_min,json=bandwidthMin,proto3" json:"bandwidth_min,omitempty"`
	BandwidthMax    uint32                 `protobuf:"varint,7,opt,name=bandwidth_max,json=bandwidthMax,proto3" json:"bandwidth_max,omitempty"`
	StartsAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	StopsAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=stops_at,json=stopsAt,proto3" json:"stops_at,omitempty"`
	TimeGranularity uint32                 `protobuf:"varint,10,opt,name=time_granularity,json=timeGranularity,proto3" json:"time_granularity,omitempty"`
	TimeMinDuration uint32                 `protobuf:"varint,11,opt,name=time_min_duration,json=timeMinDuration,proto3" json:"time_min_duration,omitempty"`
	TimeMaxDuration uint32                 `protobuf:"varint,12,opt,name=time_max_duration,json=timeMaxDuration,proto3" json:"time_max_duration,omitempty"`
	Price           uint32                 `protobuf:"varint,13,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchAsset) Reset() {
	*x = SearchAsset{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAsset) ProtoMessage() {}

func (x *SearchAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAsset.ProtoReflect.Descriptor instead.
func (*SearchAsset) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{21}
}

func (x *SearchAsset) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

func (x *SearchAsset) GetIa() uint64 {
	if x != nil {
		return x.Ia
	}
	return 0
}

func (x *SearchAsset) GetIfIdIngress() uint32 {
	if x != nil && x.IfIdIngress != nil {
		return *x.IfIdIngress
	}
	return 0
}

func (x *SearchAsset) GetIfIdEgress() uint32 {
	if x != nil && x.IfIdEgress != nil {
		return *x.IfIdEgress
	}
	return 0
}

func (x *SearchAsset) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *SearchAsset) GetBandwidthMin() uint32 {
	if x != nil {
		return x.BandwidthMin
	}
	return 0
}

func (x *SearchAsset) GetBandwidthMax() uint32 {
	if x != nil {
		return x.BandwidthMax
	}
	return 0
}

func (x *SearchAsset) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *SearchAsset) GetStopsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StopsAt
	}
	return nil
}

func (x *SearchAsset) GetTimeGranularity() uint32 {
	if x != nil {
		return x.TimeGranularity
	}
	return 0
}

func (x *SearchAsset) GetTimeMinDuration() uint32 {
	if x != nil {
		return x.TimeMinDuration
	}
	return 0
}

func (x *SearchAsset) GetTimeMaxDuration() uint32 {
	if x != nil {
		return x.TimeMaxDuration
	}
	return 0
}

func (x *SearchAsset) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BuyAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*BuyAsset            `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	MaxPrice      uint64                 `protobuf:"varint,2,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAssetsRequest) Reset() {
	*x = BuyAssetsRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAssetsRequest) ProtoMessage() {}

func (x *BuyAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAssetsRequest.ProtoReflect.Descriptor instead.
func (*BuyAssetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{22}
}

func (x *BuyAssetsRequest) GetAssets() []*BuyAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *BuyAssetsRequest) GetMaxPrice() uint64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type BuyAsset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssetId         []byte                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	StartsAtExactly *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=starts_at_exactly,json=startsAtExactly,proto3" json:"starts_at_exactly,omitempty"`
	StopsAtExactly  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=stops_at_exactly,json=stopsAtExactly,proto3" json:"stops_at_exactly,omitempty"`
	BandwidthExact  uint32                 `protobuf:"varint,4,opt,name=bandwidth_exact,json=bandwidthExact,proto3" json:"bandwidth_exact,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuyAsset) Reset() {
	*x = BuyAsset{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAsset) ProtoMessage() {}

func (x *BuyAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAsset.ProtoReflect.Descriptor instead.
func (*BuyAsset) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{23}
}

func (x *BuyAsset) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

func (x *BuyAsset) GetStartsAtExactly() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAtExactly
	}
	return nil
}

func (x *BuyAsset) GetStopsAtExactly() *timestamppb.Timestamp {
	if x != nil {
		return x.StopsAtExactly
	}
	return nil
}

func (x *BuyAsset) GetBandwidthExact() uint32 {
	if x != nil {
		return x.BandwidthExact
	}
	return 0
}

type BuyAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*BoughtAsset         `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Cost          uint64                 `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAssetsResponse) Reset() {
	*x = BuyAssetsResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAssetsResponse) ProtoMessage() {}

func (x *BuyAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAssetsResponse.ProtoReflect.Descriptor instead.
func (*BuyAssetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{24}
}

func (x *BuyAssetsResponse) GetAssets() []*BoughtAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *BuyAssetsResponse) GetCost() uint64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type BoughtAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       []byte                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoughtAsset) Reset() {
	*x = BoughtAsset{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoughtAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoughtAsset) ProtoMessage() {}

func (x *BoughtAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoughtAsset.ProtoReflect.Descriptor instead.
func (*BoughtAsset) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{25}
}

func (x *BoughtAsset) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

type RedeemAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Interfaces:
	//
	//	*RedeemAssetRequest_Pair
	//	*RedeemAssetRequest_IfPairAssetId
	Interfaces    isRedeemAssetRequest_Interfaces `protobuf_oneof:"interfaces"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemAssetRequest) Reset() {
	*x = RedeemAssetRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemAssetRequest) ProtoMessage() {}

func (x *RedeemAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemAssetRequest.ProtoReflect.Descriptor instead.
func (*RedeemAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{26}
}

func (x *RedeemAssetRequest) GetInterfaces() isRedeemAssetRequest_Interfaces {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *RedeemAssetRequest) GetPair() *IngressEgressPair {
	if x != nil {
		if x, ok := x.Interfaces.(*RedeemAssetRequest_Pair); ok {
			return x.Pair
		}
	}
	return nil
}

func (x *RedeemAssetRequest) GetIfPairAssetId() []byte {
	if x != nil {
		if x, ok := x.Interfaces.(*RedeemAssetRequest_IfPairAssetId); ok {
			return x.IfPairAssetId
		}
	}
	return nil
}

type isRedeemAssetRequest_Interfaces interface {
	isRedeemAssetRequest_Interfaces()
}

type RedeemAssetRequest_Pair struct {
	Pair *IngressEgressPair `protobuf:"bytes,1,opt,name=pair,proto3,oneof"`
}

type RedeemAssetRequest_IfPairAssetId struct {
	IfPairAssetId []byte `protobuf:"bytes,3,opt,name=if_pair_asset_id,json=ifPairAssetId,proto3,oneof"`
}

func (*RedeemAssetRequest_Pair) isRedeemAssetRequest_Interfaces() {}

func (*RedeemAssetRequest_IfPairAssetId) isRedeemAssetRequest_Interfaces() {}

type IngressEgressPair struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IngressAssetId []byte                 `protobuf:"bytes,1,opt,name=ingress_asset_id,json=ingressAssetId,proto3" json:"ingress_asset_id,omitempty"`
	EgressAssetId  []byte                 `protobuf:"bytes,2,opt,name=egress_asset_id,json=egressAssetId,proto3" json:"egress_asset_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngressEgressPair) Reset() {
	*x = IngressEgressPair{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngressEgressPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngressEgressPair) ProtoMessage() {}

func (x *IngressEgressPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngressEgressPair.ProtoReflect.Descriptor instead.
func (*IngressEgressPair) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{27}
}

func (x *IngressEgressPair) GetIngressAssetId() []byte {
	if x != nil {
		return x.IngressAssetId
	}
	return nil
}

func (x *IngressEgressPair) GetEgressAssetId() []byte {
	if x != nil {
		return x.EgressAssetId
	}
	return nil
}

type RedeemAssetResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AuthenticationKey   []byte                 `protobuf:"bytes,1,opt,name=authentication_key,json=authenticationKey,proto3" json:"authentication_key,omitempty"`
	ReservationId       uint32                 `protobuf:"varint,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	BandwidthRounded    uint32                 `protobuf:"varint,3,opt,name=bandwidth_rounded,json=bandwidthRounded,proto3" json:"bandwidth_rounded,omitempty"`
	BwDataplaneEncoding uint32                 `protobuf:"varint,4,opt,name=bw_dataplane_encoding,json=bwDataplaneEncoding,proto3" json:"bw_dataplane_encoding,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RedeemAssetResponse) Reset() {
	*x = RedeemAssetResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemAssetResponse) ProtoMessage() {}

func (x *RedeemAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemAssetResponse.ProtoReflect.Descriptor instead.
func (*RedeemAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{28}
}

func (x *RedeemAssetResponse) GetAuthenticationKey() []byte {
	if x != nil {
		return x.AuthenticationKey
	}
	return nil
}

func (x *RedeemAssetResponse) GetReservationId() uint32 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *RedeemAssetResponse) GetBandwidthRounded() uint32 {
	if x != nil {
		return x.BandwidthRounded
	}
	return 0
}

func (x *RedeemAssetResponse) GetBwDataplaneEncoding() uint32 {
	if x != nil {
		return x.BwDataplaneEncoding
	}
	return 0
}

type FetchReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ia            *uint64                `protobuf:"varint,1,opt,name=ia,proto3,oneof" json:"ia,omitempty"`
	IngressId     *uint32                `protobuf:"varint,2,opt,name=ingress_id,json=ingressId,proto3,oneof" json:"ingress_id,omitempty"`
	EgressId      *uint32                `protobuf:"varint,3,opt,name=egress_id,json=egressId,proto3,oneof" json:"egress_id,omitempty"`
	Bandwidth     *uint32                `protobuf:"varint,4,opt,name=bandwidth,proto3,oneof" json:"bandwidth,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=starts_at,json=startsAt,proto3,oneof" json:"starts_at,omitempty"`
	StopsAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=stops_at,json=stopsAt,proto3,oneof" json:"stops_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReservationsRequest) Reset() {
	*x = FetchReservationsRequest{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReservationsRequest) ProtoMessage() {}

func (x *FetchReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReservationsRequest.ProtoReflect.Descriptor instead.
func (*FetchReservationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{29}
}

func (x *FetchReservationsRequest) GetIa() uint64 {
	if x != nil && x.Ia != nil {
		return *x.Ia
	}
	return 0
}

func (x *FetchReservationsRequest) GetIngressId() uint32 {
	if x != nil && x.IngressId != nil {
		return *x.IngressId
	}
	return 0
}

func (x *FetchReservationsRequest) GetEgressId() uint32 {
	if x != nil && x.EgressId != nil {
		return *x.EgressId
	}
	return 0
}

func (x *FetchReservationsRequest) GetBandwidth() uint32 {
	if x != nil && x.Bandwidth != nil {
		return *x.Bandwidth
	}
	return 0
}

func (x *FetchReservationsRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *FetchReservationsRequest) GetStopsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StopsAt
	}
	return nil
}

type FetchReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReservationsResponse) Reset() {
	*x = FetchReservationsResponse{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReservationsResponse) ProtoMessage() {}

func (x *FetchReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReservationsResponse.ProtoReflect.Descriptor instead.
func (*FetchReservationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{30}
}

func (x *FetchReservationsResponse) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type Reservation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReservationId     uint32                 `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Ia                uint64                 `protobuf:"varint,2,opt,name=ia,proto3" json:"ia,omitempty"`
	IngressId         uint32                 `protobuf:"varint,3,opt,name=ingress_id,json=ingressId,proto3" json:"ingress_id,omitempty"`
	EgressId          uint32                 `protobuf:"varint,4,opt,name=egress_id,json=egressId,proto3" json:"egress_id,omitempty"`
	Bandwidth         uint32                 `protobuf:"varint,5,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	DataplaneEncoding uint32                 `protobuf:"varint,6,opt,name=dataplane_encoding,json=dataplaneEncoding,proto3" json:"dataplane_encoding,omitempty"`
	StartsAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	StopsAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=stops_at,json=stopsAt,proto3" json:"stops_at,omitempty"`
	AuthenticationKey []byte                 `protobuf:"bytes,9,opt,name=authentication_key,json=authenticationKey,proto3" json:"authentication_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_marketplace_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP(), []int{31}
}

func (x *Reservation) GetReservationId() uint32 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *Reservation) GetIa() uint64 {
	if x != nil {
		return x.Ia
	}
	return 0
}

func (x *Reservation) GetIngressId() uint32 {
	if x != nil {
		return x.IngressId
	}
	return 0
}

func (x *Reservation) GetEgressId() uint32 {
	if x != nil {
		return x.EgressId
	}
	return 0
}

func (x *Reservation) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *Reservation) GetDataplaneEncoding() uint32 {
	if x != nil {
		return x.DataplaneEncoding
	}
	return 0
}

func (x *Reservation) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Reservation) GetStopsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StopsAt
	}
	return nil
}

func (x *Reservation) GetAuthenticationKey() []byte {
	if x != nil {
		return x.AuthenticationKey
	}
	return nil
}

var File_proto_hummingbird_v1_marketplace_proto protoreflect.FileDescriptor

const file_proto_hummingbird_v1_marketplace_proto_rawDesc = "" +
	"\n" +
	"&proto/hummingbird/v1/marketplace.proto\x12\x14proto.hummingbird.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x13UpdateAssetsRequest\x129\n" +
	"\x06assets\x18\x01 \x03(\v2!.proto.hummingbird.v1.AssetUpdateR\x06assets\"\xad\x01\n" +
	"\vAssetUpdate\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\x12>\n" +
	"\x06update\x18\x02 \x01(\v2$.proto.hummingbird.v1.PublisherAssetH\x00R\x06update\x126\n" +
	"\x06remove\x18\x03 \x01(\v2\x1c.proto.hummingbird.v1.RemoveH\x00R\x06removeB\v\n" +
	"\toperation\"\b\n" +
	"\x06Remove\"W\n" +
	"\x14UpdateAssetsResponse\x12?\n" +
	"\x06result\x18\x01 \x03(\v2'.proto.hummingbird.v1.UpdateAssetResultR\x06result\"S\n" +
	"\x11UpdateAssetResult\x12\x17\n" +
	"\x06new_id\x18\x01 \x01(\fH\x00R\x05newId\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\r\n" +
	"\vresult_type\"\xfa\x01\n" +
	"\x11StatisticsRequest\x12'\n" +
	"\rif_id_ingress\x18\x01 \x01(\rH\x00R\vifIdIngress\x88\x01\x01\x12%\n" +
	"\fif_id_egress\x18\x02 \x01(\rH\x01R\n" +
	"ifIdEgress\x88\x01\x01\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x12\n" +
	"\x04step\x18\x05 \x01(\rR\x04stepB\x10\n" +
	"\x0e_if_id_ingressB\x0f\n" +
	"\r_if_id_egress\"c\n" +
	"\x12StatisticsResponse\x12M\n" +
	"\n" +
	"statistics\x18\x01 \x03(\v2-.proto.hummingbird.v1.StatisticsResponseEntryR\n" +
	"statistics\"h\n" +
	"\x17StatisticsResponseEntry\x12\x18\n" +
	"\arevenue\x18\x01 \x01(\x04R\arevenue\x123\n" +
	"\x15bandwidth_utilization\x18\x02 \x01(\x01R\x14bandwidthUtilization\"\xc8\x01\n" +
	"\x11SplitAssetRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\x12@\n" +
	"\bbw_split\x18\x02 \x01(\v2#.proto.hummingbird.v1.SplitBwOptionH\x00R\abwSplit\x12F\n" +
	"\n" +
	"time_split\x18\x03 \x01(\v2%.proto.hummingbird.v1.SplitTimeOptionH\x00R\ttimeSplitB\x0e\n" +
	"\fsplit_option\"'\n" +
	"\rSplitBwOption\x12\x16\n" +
	"\x06splits\x18\x01 \x03(\rR\x06splits\"E\n" +
	"\x0fSplitTimeOption\x122\n" +
	"\x06splits\x18\x01 \x03(\v2\x1a.google.protobuf.TimestampR\x06splits\"1\n" +
	"\x12SplitAssetResponse\x12\x1b\n" +
	"\tasset_ids\x18\x01 \x03(\fR\bassetIds\"2\n" +
	"\x13CombineAssetRequest\x12\x1b\n" +
	"\tasset_ids\x18\x01 \x03(\fR\bassetIds\"1\n" +
	"\x14CombineAssetResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\"\x18\n" +
	"\x16MarketplaceInfoRequest\"\xa3\x05\n" +
	"\x17MarketplaceInfoResponse\x12*\n" +
	"\x11api_major_version\x18\x01 \x01(\rR\x0fapiMajorVersion\x12*\n" +
	"\x11api_minor_version\x18\x02 \x01(\rR\x0fapiMinorVersion\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12+\n" +
	"\x11currency_exponent\x18\x04 \x01(\rR\x10currencyExponent\x12<\n" +
	"\x1amax_statistics_granularity\x18\x05 \x01(\rR\x18maxStatisticsGranularity\x12P\n" +
	"\x10pricing_strategy\x18\x06 \x01(\x0e2%.proto.hummingbird.v1.PricingStrategyR\x0fpricingStrategy\x128\n" +
	"\x18transaction_fee_relative\x18\a \x01(\x02R\x16transactionFeeRelative\x128\n" +
	"\x18transaction_fee_absolute\x18\b \x01(\x04R\x16transactionFeeAbsolute\x12;\n" +
	"\x1asplit_combine_fee_absolute\x18\t \x01(\x04R\x17splitCombineFeeAbsolute\x12D\n" +
	"\x1esupports_redemption_delegation\x18\n" +
	" \x01(\bR\x1csupportsRedemptionDelegation\x122\n" +
	"\x15delegation_hourly_fee\x18\v \x01(\x04R\x13delegationHourlyFee\x12,\n" +
	"\x12asset_validity_max\x18\f \x01(\rR\x10assetValidityMax\"Q\n" +
	"\x13PublishAssetRequest\x12:\n" +
	"\x05asset\x18\x01 \x01(\v2$.proto.hummingbird.v1.PublisherAssetR\x05asset\"1\n" +
	"\x14PublishAssetResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\"\xf4\x03\n" +
	"\x0ePublisherAsset\x12'\n" +
	"\rif_id_ingress\x18\x01 \x01(\rH\x00R\vifIdIngress\x88\x01\x01\x12%\n" +
	"\fif_id_egress\x18\x02 \x01(\rH\x01R\n" +
	"ifIdEgress\x88\x01\x01\x12\x1c\n" +
	"\tbandwidth\x18\x03 \x01(\rR\tbandwidth\x12#\n" +
	"\rbandwidth_min\x18\x04 \x01(\rR\fbandwidthMin\x12#\n" +
	"\rbandwidth_max\x18\x05 \x01(\rR\fbandwidthMax\x127\n" +
	"\tstarts_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x125\n" +
	"\bstops_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\astopsAt\x12)\n" +
	"\x10time_granularity\x18\b \x01(\rR\x0ftimeGranularity\x12*\n" +
	"\x11time_min_duration\x18\t \x01(\rR\x0ftimeMinDuration\x12*\n" +
	"\x11time_max_duration\x18\n" +
	" \x01(\rR\x0ftimeMaxDuration\x12\x14\n" +
	"\x05price\x18\v \x01(\rR\x05priceB\x10\n" +
	"\x0e_if_id_ingressB\x0f\n" +
	"\r_if_id_egress\"\xc4\x04\n" +
	"\x13SearchAssetsRequest\x12\x14\n" +
	"\x05owned\x18\x01 \x01(\bR\x05owned\x12\x13\n" +
	"\x02ia\x18\x02 \x01(\x04H\x00R\x02ia\x88\x01\x01\x12'\n" +
	"\rif_id_ingress\x18\x03 \x01(\rH\x01R\vifIdIngress\x88\x01\x01\x12%\n" +
	"\fif_id_egress\x18\x04 \x01(\rH\x02R\n" +
	"ifIdEgress\x88\x01\x01\x12+\n" +
	"\x0fmin_required_bw\x18\x05 \x01(\rH\x03R\rminRequiredBw\x88\x01\x01\x12I\n" +
	"\x10starts_at_latest\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x0estartsAtLatest\x88\x01\x01\x12K\n" +
	"\x11stops_at_earliest\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x05R\x0fstopsAtEarliest\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\b \x01(\rH\x06R\x05price\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\t \x01(\rR\x04page\x123\n" +
	"\x13max_returned_assets\x18\n" +
	" \x01(\rH\aR\x11maxReturnedAssets\x88\x01\x01B\x05\n" +
	"\x03_iaB\x10\n" +
	"\x0e_if_id_ingressB\x0f\n" +
	"\r_if_id_egressB\x12\n" +
	"\x10_min_required_bwB\x13\n" +
	"\x11_starts_at_latestB\x14\n" +
	"\x12_stops_at_earliestB\b\n" +
	"\x06_priceB\x16\n" +
	"\x14_max_returned_assets\"Q\n" +
	"\x14SearchAssetsResponse\x129\n" +
	"\x06assets\x18\x01 \x03(\v2!.proto.hummingbird.v1.SearchAssetR\x06assets\"\x9c\x04\n" +
	"\vSearchAsset\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\x12\x0e\n" +
	"\x02ia\x18\x02 \x01(\x04R\x02ia\x12'\n" +
	"\rif_id_ingress\x18\x03 \x01(\rH\x00R\vifIdIngress\x88\x01\x01\x12%\n" +
	"\fif_id_egress\x18\x04 \x01(\rH\x01R\n" +
	"ifIdEgress\x88\x01\x01\x12\x1c\n" +
	"\tbandwidth\x18\x05 \x01(\rR\tbandwidth\x12#\n" +
	"\rbandwidth_min\x18\x06 \x01(\rR\fbandwidthMin\x12#\n" +
	"\rbandwidth_max\x18\a \x01(\rR\fbandwidthMax\x127\n" +
	"\tstarts_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x125\n" +
	"\bstops_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\astopsAt\x12)\n" +
	"\x10time_granularity\x18\n" +
	" \x01(\rR\x0ftimeGranularity\x12*\n" +
	"\x11time_min_duration\x18\v \x01(\rR\x0ftimeMinDuration\x12*\n" +
	"\x11time_max_duration\x18\f \x01(\rR\x0ftimeMaxDuration\x12\x14\n" +
	"\x05price\x18\r \x01(\rR\x05priceB\x10\n" +
	"\x0e_if_id_ingressB\x0f\n" +
	"\r_if_id_egress\"g\n" +
	"\x10BuyAssetsRequest\x126\n" +
	"\x06assets\x18\x01 \x03(\v2\x1e.proto.hummingbird.v1.BuyAssetR\x06assets\x12\x1b\n" +
	"\tmax_price\x18\x02 \x01(\x04R\bmaxPrice\"\xdc\x01\n" +
	"\bBuyAsset\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\x12F\n" +
	"\x11starts_at_exactly\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fstartsAtExactly\x12D\n" +
	"\x10stops_at_exactly\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0estopsAtExactly\x12'\n" +
	"\x0fbandwidth_exact\x18\x04 \x01(\rR\x0ebandwidthExact\"b\n" +
	"\x11BuyAssetsResponse\x129\n" +
	"\x06assets\x18\x01 \x03(\v2!.proto.hummingbird.v1.BoughtAssetR\x06assets\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x04R\x04cost\"(\n" +
	"\vBoughtAsset\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\"\x8c\x01\n" +
	"\x12RedeemAssetRequest\x12=\n" +
	"\x04pair\x18\x01 \x01(\v2'.proto.hummingbird.v1.IngressEgressPairH\x00R\x04pair\x12)\n" +
	"\x10if_pair_asset_id\x18\x03 \x01(\fH\x00R\rifPairAssetIdB\f\n" +
	"\n" +
	"interfaces\"e\n" +
	"\x11IngressEgressPair\x12(\n" +
	"\x10ingress_asset_id\x18\x01 \x01(\fR\x0eingressAssetId\x12&\n" +
	"\x0fegress_asset_id\x18\x02 \x01(\fR\regressAssetId\"\xcc\x01\n" +
	"\x13RedeemAssetResponse\x12-\n" +
	"\x12authentication_key\x18\x01 \x01(\fR\x11authenticationKey\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\rR\rreservationId\x12+\n" +
	"\x11bandwidth_rounded\x18\x03 \x01(\rR\x10bandwidthRounded\x122\n" +
	"\x15bw_dataplane_encoding\x18\x04 \x01(\rR\x13bwDataplaneEncoding\"\xdf\x02\n" +
	"\x18FetchReservationsRequest\x12\x13\n" +
	"\x02ia\x18\x01 \x01(\x04H\x00R\x02ia\x88\x01\x01\x12\"\n" +
	"\n" +
	"ingress_id\x18\x02 \x01(\rH\x01R\tingressId\x88\x01\x01\x12 \n" +
	"\tegress_id\x18\x03 \x01(\rH\x02R\begressId\x88\x01\x01\x12!\n" +
	"\tbandwidth\x18\x04 \x01(\rH\x03R\tbandwidth\x88\x01\x01\x12<\n" +
	"\tstarts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\bstartsAt\x88\x01\x01\x12:\n" +
	"\bstops_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x05R\astopsAt\x88\x01\x01B\x05\n" +
	"\x03_iaB\r\n" +
	"\v_ingress_idB\f\n" +
	"\n" +
	"_egress_idB\f\n" +
	"\n" +
	"_bandwidthB\f\n" +
	"\n" +
	"_starts_atB\v\n" +
	"\t_stops_at\"b\n" +
	"\x19FetchReservationsResponse\x12E\n" +
	"\freservations\x18\x01 \x03(\v2!.proto.hummingbird.v1.ReservationR\freservations\"\xec\x02\n" +
	"\vReservation\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\rR\rreservationId\x12\x0e\n" +
	"\x02ia\x18\x02 \x01(\x04R\x02ia\x12\x1d\n" +
	"\n" +
	"ingress_id\x18\x03 \x01(\rR\tingressId\x12\x1b\n" +
	"\tegress_id\x18\x04 \x01(\rR\begressId\x12\x1c\n" +
	"\tbandwidth\x18\x05 \x01(\rR\tbandwidth\x12-\n" +
	"\x12dataplane_encoding\x18\x06 \x01(\rR\x11dataplaneEncoding\x127\n" +
	"\tstarts_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x125\n" +
	"\bstops_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\astopsAt\x12-\n" +
	"\x12authentication_key\x18\t \x01(\fR\x11authenticationKey*:\n" +
	"\x0fPricingStrategy\x12\x12\n" +
	"\x0estatic_pricing\x10\x00\x12\x13\n" +
	"\x0fdynamic_pricing\x10\x012\xa4\b\n" +
	"\x12MarketplaceService\x12e\n" +
	"\x04Info\x12,.proto.hummingbird.v1.MarketplaceInfoRequest\x1a-.proto.hummingbird.v1.MarketplaceInfoResponse\"\x00\x12g\n" +
	"\fPublishAsset\x12).proto.hummingbird.v1.PublishAssetRequest\x1a*.proto.hummingbird.v1.PublishAssetResponse\"\x00\x12g\n" +
	"\fSearchAssets\x12).proto.hummingbird.v1.SearchAssetsRequest\x1a*.proto.hummingbird.v1.SearchAssetsResponse\"\x00\x12^\n" +
	"\tBuyAssets\x12&.proto.hummingbird.v1.BuyAssetsRequest\x1a'.proto.hummingbird.v1.BuyAssetsResponse\"\x00\x12d\n" +
	"\vRedeemAsset\x12(.proto.hummingbird.v1.RedeemAssetRequest\x1a).proto.hummingbird.v1.RedeemAssetResponse\"\x00\x12v\n" +
	"\x11FetchReservations\x12..proto.hummingbird.v1.FetchReservationsRequest\x1a/.proto.hummingbird.v1.FetchReservationsResponse\"\x00\x12a\n" +
	"\n" +
	"SplitAsset\x12'.proto.hummingbird.v1.SplitAssetRequest\x1a(.proto.hummingbird.v1.SplitAssetResponse\"\x00\x12h\n" +
	"\rCombineAssets\x12).proto.hummingbird.v1.CombineAssetRequest\x1a*.proto.hummingbird.v1.CombineAssetResponse\"\x00\x12a\n" +
	"\n" +
	"Statistics\x12'.proto.hummingbird.v1.StatisticsRequest\x1a(.proto.hummingbird.v1.StatisticsResponse\"\x00\x12g\n" +
	"\fUpdateAssets\x12).proto.hummingbird.v1.UpdateAssetsRequest\x1a*.proto.hummingbird.v1.UpdateAssetsResponse\"\x00B3Z1github.com/scionproto/scion/pkg/proto/hummingbirdb\x06proto3"

var (
	file_proto_hummingbird_v1_marketplace_proto_rawDescOnce sync.Once
	file_proto_hummingbird_v1_marketplace_proto_rawDescData []byte
)

func file_proto_hummingbird_v1_marketplace_proto_rawDescGZIP() []byte {
	file_proto_hummingbird_v1_marketplace_proto_rawDescOnce.Do(func() {
		file_proto_hummingbird_v1_marketplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hummingbird_v1_marketplace_proto_rawDesc), len(file_proto_hummingbird_v1_marketplace_proto_rawDesc)))
	})
	return file_proto_hummingbird_v1_marketplace_proto_rawDescData
}

var file_proto_hummingbird_v1_marketplace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_hummingbird_v1_marketplace_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_hummingbird_v1_marketplace_proto_goTypes = []any{
	(PricingStrategy)(0),              // 0: proto.hummingbird.v1.PricingStrategy
	(*UpdateAssetsRequest)(nil),       // 1: proto.hummingbird.v1.UpdateAssetsRequest
	(*AssetUpdate)(nil),               // 2: proto.hummingbird.v1.AssetUpdate
	(*Remove)(nil),                    // 3: proto.hummingbird.v1.Remove
	(*UpdateAssetsResponse)(nil),      // 4: proto.hummingbird.v1.UpdateAssetsResponse
	(*UpdateAssetResult)(nil),         // 5: proto.hummingbird.v1.UpdateAssetResult
	(*StatisticsRequest)(nil),         // 6: proto.hummingbird.v1.StatisticsRequest
	(*StatisticsResponse)(nil),        // 7: proto.hummingbird.v1.StatisticsResponse
	(*StatisticsResponseEntry)(nil),   // 8: proto.hummingbird.v1.StatisticsResponseEntry
	(*SplitAssetRequest)(nil),         // 9: proto.hummingbird.v1.SplitAssetRequest
	(*SplitBwOption)(nil),             // 10: proto.hummingbird.v1.SplitBwOption
	(*SplitTimeOption)(nil),           // 11: proto.hummingbird.v1.SplitTimeOption
	(*SplitAssetResponse)(nil),        // 12: proto.hummingbird.v1.SplitAssetResponse
	(*CombineAssetRequest)(nil),       // 13: proto.hummingbird.v1.CombineAssetRequest
	(*CombineAssetResponse)(nil),      // 14: proto.hummingbird.v1.CombineAssetResponse
	(*MarketplaceInfoRequest)(nil),    // 15: proto.hummingbird.v1.MarketplaceInfoRequest
	(*MarketplaceInfoResponse)(nil),   // 16: proto.hummingbird.v1.MarketplaceInfoResponse
	(*PublishAssetRequest)(nil),       // 17: proto.hummingbird.v1.PublishAssetRequest
	(*PublishAssetResponse)(nil),      // 18: proto.hummingbird.v1.PublishAssetResponse
	(*PublisherAsset)(nil),            // 19: proto.hummingbird.v1.PublisherAsset
	(*SearchAssetsRequest)(nil),       // 20: proto.hummingbird.v1.SearchAssetsRequest
	(*SearchAssetsResponse)(nil),      // 21: proto.hummingbird.v1.SearchAssetsResponse
	(*SearchAsset)(nil),               // 22: proto.hummingbird.v1.SearchAsset
	(*BuyAssetsRequest)(nil),          // 23: proto.hummingbird.v1.BuyAssetsRequest
	(*BuyAsset)(nil),                  // 24: proto.hummingbird.v1.BuyAsset
	(*BuyAssetsResponse)(nil),         // 25: proto.hummingbird.v1.BuyAssetsResponse
	(*BoughtAsset)(nil),               // 26: proto.hummingbird.v1.BoughtAsset
	(*RedeemAssetRequest)(nil),        // 27: proto.hummingbird.v1.RedeemAssetRequest
	(*IngressEgressPair)(nil),         // 28: proto.hummingbird.v1.IngressEgressPair
	(*RedeemAssetResponse)(nil),       // 29: proto.hummingbird.v1.RedeemAssetResponse
	(*FetchReservationsRequest)(nil),  // 30: proto.hummingbird.v1.FetchReservationsRequest
	(*FetchReservationsResponse)(nil), // 31: proto.hummingbird.v1.FetchReservationsResponse
	(*Reservation)(nil),               // 32: proto.hummingbird.v1.Reservation
	(*timestamppb.Timestamp)(nil),     // 33: google.protobuf.Timestamp
}
var file_proto_hummingbird_v1_marketplace_proto_depIdxs = []int32{
	2,  // 0: proto.hummingbird.v1.UpdateAssetsRequest.assets:type_name -> proto.hummingbird.v1.AssetUpdate
	19, // 1: proto.hummingbird.v1.AssetUpdate.update:type_name -> proto.hummingbird.v1.PublisherAsset
	3,  // 2: proto.hummingbird.v1.AssetUpdate.remove:type_name -> proto.hummingbird.v1.Remove
	5,  // 3: proto.hummingbird.v1.UpdateAssetsResponse.result:type_name -> proto.hummingbird.v1.UpdateAssetResult
	33, // 4: proto.hummingbird.v1.StatisticsRequest.start:type_name -> google.protobuf.Timestamp
	33, // 5: proto.hummingbird.v1.StatisticsRequest.end:type_name -> google.protobuf.Timestamp
	8,  // 6: proto.hummingbird.v1.StatisticsResponse.statistics:type_name -> proto.hummingbird.v1.StatisticsResponseEntry
	10, // 7: proto.hummingbird.v1.SplitAssetRequest.bw_split:type_name -> proto.hummingbird.v1.SplitBwOption
	11, // 8: proto.hummingbird.v1.SplitAssetRequest.time_split:type_name -> proto.hummingbird.v1.SplitTimeOption
	33, // 9: proto.hummingbird.v1.SplitTimeOption.splits:type_name -> google.protobuf.Timestamp
	0,  // 10: proto.hummingbird.v1.MarketplaceInfoResponse.pricing_strategy:type_name -> proto.hummingbird.v1.PricingStrategy
	19, // 11: proto.hummingbird.v1.PublishAssetRequest.asset:type_name -> proto.hummingbird.v1.PublisherAsset
	33, // 12: proto.hummingbird.v1.PublisherAsset.starts_at:type_name -> google.protobuf.Timestamp
	33, // 13: proto.hummingbird.v1.PublisherAsset.stops_at:type_name -> google.protobuf.Timestamp
	33, // 14: proto.hummingbird.v1.SearchAssetsRequest.starts_at_latest:type_name -> google.protobuf.Timestamp
	33, // 15: proto.hummingbird.v1.SearchAssetsRequest.stops_at_earliest:type_name -> google.protobuf.Timestamp
	22, // 16: proto.hummingbird.v1.SearchAssetsResponse.assets:type_name -> proto.hummingbird.v1.SearchAsset
	33, // 17: proto.hummingbird.v1.SearchAsset.starts_at:type_name -> google.protobuf.Timestamp
	33, // 18: proto.hummingbird.v1.SearchAsset.stops_at:type_name -> google.protobuf.Timestamp
	24, // 19: proto.hummingbird.v1.BuyAssetsRequest.assets:type_name -> proto.hummingbird.v1.BuyAsset
	33, // 20: proto.hummingbird.v1.BuyAsset.starts_at_exactly:type_name -> google.protobuf.Timestamp
	33, // 21: proto.hummingbird.v1.BuyAsset.stops_at_exactly:type_name -> google.protobuf.Timestamp
	26, // 22: proto.hummingbird.v1.BuyAssetsResponse.assets:type_name -> proto.hummingbird.v1.BoughtAsset
	28, // 23: proto.hummingbird.v1.RedeemAssetRequest.pair:type_name -> proto.hummingbird.v1.IngressEgressPair
	33, // 24: proto.hummingbird.v1.FetchReservationsRequest.starts_at:type_name -> google.protobuf.Timestamp
	33, // 25: proto.hummingbird.v1.FetchReservationsRequest.stops_at:type_name -> google.protobuf.Timestamp
	32, // 26: proto.hummingbird.v1.FetchReservationsResponse.reservations:type_name -> proto.hummingbird.v1.Reservation
	33, // 27: proto.hummingbird.v1.Reservation.starts_at:type_name -> google.protobuf.Timestamp
	33, // 28: proto.hummingbird.v1.Reservation.stops_at:type_name -> google.protobuf.Timestamp
	15, // 29: proto.hummingbird.v1.MarketplaceService.Info:input_type -> proto.hummingbird.v1.MarketplaceInfoRequest
	17, // 30: proto.hummingbird.v1.MarketplaceService.PublishAsset:input_type -> proto.hummingbird.v1.PublishAssetRequest
	20, // 31: proto.hummingbird.v1.MarketplaceService.SearchAssets:input_type -> proto.hummingbird.v1.SearchAssetsRequest
	23, // 32: proto.hummingbird.v1.MarketplaceService.BuyAssets:input_type -> proto.hummingbird.v1.BuyAssetsRequest
	27, // 33: proto.hummingbird.v1.MarketplaceService.RedeemAsset:input_type -> proto.hummingbird.v1.RedeemAssetRequest
	30, // 34: proto.hummingbird.v1.MarketplaceService.FetchReservations:input_type -> proto.hummingbird.v1.FetchReservationsRequest
	9,  // 35: proto.hummingbird.v1.MarketplaceService.SplitAsset:input_type -> proto.hummingbird.v1.SplitAssetRequest
	13, // 36: proto.hummingbird.v1.MarketplaceService.CombineAssets:input_type -> proto.hummingbird.v1.CombineAssetRequest
	6,  // 37: proto.hummingbird.v1.MarketplaceService.Statistics:input_type -> proto.hummingbird.v1.StatisticsRequest
	1,  // 38: proto.hummingbird.v1.MarketplaceService.UpdateAssets:input_type -> proto.hummingbird.v1.UpdateAssetsRequest
	16, // 39: proto.hummingbird.v1.MarketplaceService.Info:output_type -> proto.hummingbird.v1.MarketplaceInfoResponse
	18, // 40: proto.hummingbird.v1.MarketplaceService.PublishAsset:output_type -> proto.hummingbird.v1.PublishAssetResponse
	21, // 41: proto.hummingbird.v1.MarketplaceService.SearchAssets:output_type -> proto.hummingbird.v1.SearchAssetsResponse
	25, // 42: proto.hummingbird.v1.MarketplaceService.BuyAssets:output_type -> proto.hummingbird.v1.BuyAssetsResponse
	29, // 43: proto.hummingbird.v1.MarketplaceService.RedeemAsset:output_type -> proto.hummingbird.v1.RedeemAssetResponse
	31, // 44: proto.hummingbird.v1.MarketplaceService.FetchReservations:output_type -> proto.hummingbird.v1.FetchReservationsResponse
	12, // 45: proto.hummingbird.v1.MarketplaceService.SplitAsset:output_type -> proto.hummingbird.v1.SplitAssetResponse
	14, // 46: proto.hummingbird.v1.MarketplaceService.CombineAssets:output_type -> proto.hummingbird.v1.CombineAssetResponse
	7,  // 47: proto.hummingbird.v1.MarketplaceService.Statistics:output_type -> proto.hummingbird.v1.StatisticsResponse
	4,  // 48: proto.hummingbird.v1.MarketplaceService.UpdateAssets:output_type -> proto.hummingbird.v1.UpdateAssetsResponse
	39, // [39:49] is the sub-list for method output_type
	29, // [29:39] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_hummingbird_v1_marketplace_proto_init() }
func file_proto_hummingbird_v1_marketplace_proto_init() {
	if File_proto_hummingbird_v1_marketplace_proto != nil {
		return
	}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[1].OneofWrappers = []any{
		(*AssetUpdate_Update)(nil),
		(*AssetUpdate_Remove)(nil),
	}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[4].OneofWrappers = []any{
		(*UpdateAssetResult_NewId)(nil),
		(*UpdateAssetResult_Error)(nil),
	}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[8].OneofWrappers = []any{
		(*SplitAssetRequest_BwSplit)(nil),
		(*SplitAssetRequest_TimeSplit)(nil),
	}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[18].OneofWrappers = []any{}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[19].OneofWrappers = []any{}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[21].OneofWrappers = []any{}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[26].OneofWrappers = []any{
		(*RedeemAssetRequest_Pair)(nil),
		(*RedeemAssetRequest_IfPairAssetId)(nil),
	}
	file_proto_hummingbird_v1_marketplace_proto_msgTypes[29].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hummingbird_v1_marketplace_proto_rawDesc), len(file_proto_hummingbird_v1_marketplace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hummingbird_v1_marketplace_proto_goTypes,
		DependencyIndexes: file_proto_hummingbird_v1_marketplace_proto_depIdxs,
		EnumInfos:         file_proto_hummingbird_v1_marketplace_proto_enumTypes,
		MessageInfos:      file_proto_hummingbird_v1_marketplace_proto_msgTypes,
	}.Build()
	File_proto_hummingbird_v1_marketplace_proto = out.File
	file_proto_hummingbird_v1_marketplace_proto_goTypes = nil
	file_proto_hummingbird_v1_marketplace_proto_depIdxs = nil
}
