// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/hummingbird/v1/redemption.proto

package hummingbird

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelegateRedemptionRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ExpirationTime          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	ReservationIdUpperBound uint64                 `protobuf:"varint,2,opt,name=reservation_id_upper_bound,json=reservationIdUpperBound,proto3" json:"reservation_id_upper_bound,omitempty"`
	Key                     []byte                 `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DelegateRedemptionRequest) Reset() {
	*x = DelegateRedemptionRequest{}
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateRedemptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateRedemptionRequest) ProtoMessage() {}

func (x *DelegateRedemptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateRedemptionRequest.ProtoReflect.Descriptor instead.
func (*DelegateRedemptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_redemption_proto_rawDescGZIP(), []int{0}
}

func (x *DelegateRedemptionRequest) GetExpirationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

func (x *DelegateRedemptionRequest) GetReservationIdUpperBound() uint64 {
	if x != nil {
		return x.ReservationIdUpperBound
	}
	return 0
}

func (x *DelegateRedemptionRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DelegateRedemptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpirationTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DelegateRedemptionResponse) Reset() {
	*x = DelegateRedemptionResponse{}
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateRedemptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateRedemptionResponse) ProtoMessage() {}

func (x *DelegateRedemptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateRedemptionResponse.ProtoReflect.Descriptor instead.
func (*DelegateRedemptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_redemption_proto_rawDescGZIP(), []int{1}
}

func (x *DelegateRedemptionResponse) GetExpirationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

type RedeemAssetFromASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngressId     uint32                 `protobuf:"varint,1,opt,name=ingress_id,json=ingressId,proto3" json:"ingress_id,omitempty"`
	EgressId      uint32                 `protobuf:"varint,2,opt,name=egress_id,json=egressId,proto3" json:"egress_id,omitempty"`
	Bw            uint64                 `protobuf:"varint,3,opt,name=bw,proto3" json:"bw,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	StopsAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=stops_at,json=stopsAt,proto3" json:"stops_at,omitempty"`
	RequestId     uint64                 `protobuf:"varint,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemAssetFromASRequest) Reset() {
	*x = RedeemAssetFromASRequest{}
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemAssetFromASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemAssetFromASRequest) ProtoMessage() {}

func (x *RedeemAssetFromASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemAssetFromASRequest.ProtoReflect.Descriptor instead.
func (*RedeemAssetFromASRequest) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_redemption_proto_rawDescGZIP(), []int{2}
}

func (x *RedeemAssetFromASRequest) GetIngressId() uint32 {
	if x != nil {
		return x.IngressId
	}
	return 0
}

func (x *RedeemAssetFromASRequest) GetEgressId() uint32 {
	if x != nil {
		return x.EgressId
	}
	return 0
}

func (x *RedeemAssetFromASRequest) GetBw() uint64 {
	if x != nil {
		return x.Bw
	}
	return 0
}

func (x *RedeemAssetFromASRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *RedeemAssetFromASRequest) GetStopsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StopsAt
	}
	return nil
}

func (x *RedeemAssetFromASRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type RedeemAssetFromASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResInfo       *ReservationInfo       `protobuf:"bytes,1,opt,name=res_info,json=resInfo,proto3" json:"res_info,omitempty"`
	Ak            string                 `protobuf:"bytes,2,opt,name=ak,proto3" json:"ak,omitempty"`
	RequestId     uint64                 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemAssetFromASResponse) Reset() {
	*x = RedeemAssetFromASResponse{}
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemAssetFromASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemAssetFromASResponse) ProtoMessage() {}

func (x *RedeemAssetFromASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemAssetFromASResponse.ProtoReflect.Descriptor instead.
func (*RedeemAssetFromASResponse) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_redemption_proto_rawDescGZIP(), []int{3}
}

func (x *RedeemAssetFromASResponse) GetResInfo() *ReservationInfo {
	if x != nil {
		return x.ResInfo
	}
	return nil
}

func (x *RedeemAssetFromASResponse) GetAk() string {
	if x != nil {
		return x.Ak
	}
	return ""
}

func (x *RedeemAssetFromASResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type ReservationInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResId               uint64                 `protobuf:"varint,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	BwRounded           uint64                 `protobuf:"varint,2,opt,name=bw_rounded,json=bwRounded,proto3" json:"bw_rounded,omitempty"`
	BwDataplaneEncoding uint32                 `protobuf:"varint,3,opt,name=bw_dataplane_encoding,json=bwDataplaneEncoding,proto3" json:"bw_dataplane_encoding,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReservationInfo) Reset() {
	*x = ReservationInfo{}
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationInfo) ProtoMessage() {}

func (x *ReservationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hummingbird_v1_redemption_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationInfo.ProtoReflect.Descriptor instead.
func (*ReservationInfo) Descriptor() ([]byte, []int) {
	return file_proto_hummingbird_v1_redemption_proto_rawDescGZIP(), []int{4}
}

func (x *ReservationInfo) GetResId() uint64 {
	if x != nil {
		return x.ResId
	}
	return 0
}

func (x *ReservationInfo) GetBwRounded() uint64 {
	if x != nil {
		return x.BwRounded
	}
	return 0
}

func (x *ReservationInfo) GetBwDataplaneEncoding() uint32 {
	if x != nil {
		return x.BwDataplaneEncoding
	}
	return 0
}

var File_proto_hummingbird_v1_redemption_proto protoreflect.FileDescriptor

const file_proto_hummingbird_v1_redemption_proto_rawDesc = "" +
	"\n" +
	"%proto/hummingbird/v1/redemption.proto\x12\x14proto.hummingbird.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\x19DelegateRedemptionRequest\x12C\n" +
	"\x0fexpiration_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationTime\x12;\n" +
	"\x1areservation_id_upper_bound\x18\x02 \x01(\x04R\x17reservationIdUpperBound\x12\x10\n" +
	"\x03Key\x18\x03 \x01(\fR\x03Key\"a\n" +
	"\x1aDelegateRedemptionResponse\x12C\n" +
	"\x0fexpiration_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationTime\"\xf5\x01\n" +
	"\x18RedeemAssetFromASRequest\x12\x1d\n" +
	"\n" +
	"ingress_id\x18\x01 \x01(\rR\tingressId\x12\x1b\n" +
	"\tegress_id\x18\x02 \x01(\rR\begressId\x12\x0e\n" +
	"\x02bw\x18\x03 \x01(\x04R\x02bw\x127\n" +
	"\tstarts_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x125\n" +
	"\bstops_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\astopsAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\x04R\trequestId\"\x8c\x01\n" +
	"\x19RedeemAssetFromASResponse\x12@\n" +
	"\bres_info\x18\x01 \x01(\v2%.proto.hummingbird.v1.ReservationInfoR\aresInfo\x12\x0e\n" +
	"\x02ak\x18\x02 \x01(\tR\x02ak\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x04R\trequestId\"{\n" +
	"\x0fReservationInfo\x12\x15\n" +
	"\x06res_id\x18\x01 \x01(\x04R\x05resId\x12\x1d\n" +
	"\n" +
	"bw_rounded\x18\x02 \x01(\x04R\tbwRounded\x122\n" +
	"\x15bw_dataplane_encoding\x18\x03 \x01(\rR\x13bwDataplaneEncoding2\x86\x02\n" +
	"\x11RedemptionService\x12v\n" +
	"\rRedeemASAsset\x12/.proto.hummingbird.v1.RedeemAssetFromASResponse\x1a..proto.hummingbird.v1.RedeemAssetFromASRequest\"\x00(\x010\x01\x12y\n" +
	"\x12DelegateRedemption\x12/.proto.hummingbird.v1.DelegateRedemptionRequest\x1a0.proto.hummingbird.v1.DelegateRedemptionResponse\"\x00B3Z1github.com/scionproto/scion/pkg/proto/hummingbirdb\x06proto3"

var (
	file_proto_hummingbird_v1_redemption_proto_rawDescOnce sync.Once
	file_proto_hummingbird_v1_redemption_proto_rawDescData []byte
)

func file_proto_hummingbird_v1_redemption_proto_rawDescGZIP() []byte {
	file_proto_hummingbird_v1_redemption_proto_rawDescOnce.Do(func() {
		file_proto_hummingbird_v1_redemption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hummingbird_v1_redemption_proto_rawDesc), len(file_proto_hummingbird_v1_redemption_proto_rawDesc)))
	})
	return file_proto_hummingbird_v1_redemption_proto_rawDescData
}

var file_proto_hummingbird_v1_redemption_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_hummingbird_v1_redemption_proto_goTypes = []any{
	(*DelegateRedemptionRequest)(nil),  // 0: proto.hummingbird.v1.DelegateRedemptionRequest
	(*DelegateRedemptionResponse)(nil), // 1: proto.hummingbird.v1.DelegateRedemptionResponse
	(*RedeemAssetFromASRequest)(nil),   // 2: proto.hummingbird.v1.RedeemAssetFromASRequest
	(*RedeemAssetFromASResponse)(nil),  // 3: proto.hummingbird.v1.RedeemAssetFromASResponse
	(*ReservationInfo)(nil),            // 4: proto.hummingbird.v1.ReservationInfo
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_proto_hummingbird_v1_redemption_proto_depIdxs = []int32{
	5, // 0: proto.hummingbird.v1.DelegateRedemptionRequest.expiration_time:type_name -> google.protobuf.Timestamp
	5, // 1: proto.hummingbird.v1.DelegateRedemptionResponse.expiration_time:type_name -> google.protobuf.Timestamp
	5, // 2: proto.hummingbird.v1.RedeemAssetFromASRequest.starts_at:type_name -> google.protobuf.Timestamp
	5, // 3: proto.hummingbird.v1.RedeemAssetFromASRequest.stops_at:type_name -> google.protobuf.Timestamp
	4, // 4: proto.hummingbird.v1.RedeemAssetFromASResponse.res_info:type_name -> proto.hummingbird.v1.ReservationInfo
	3, // 5: proto.hummingbird.v1.RedemptionService.RedeemASAsset:input_type -> proto.hummingbird.v1.RedeemAssetFromASResponse
	0, // 6: proto.hummingbird.v1.RedemptionService.DelegateRedemption:input_type -> proto.hummingbird.v1.DelegateRedemptionRequest
	2, // 7: proto.hummingbird.v1.RedemptionService.RedeemASAsset:output_type -> proto.hummingbird.v1.RedeemAssetFromASRequest
	1, // 8: proto.hummingbird.v1.RedemptionService.DelegateRedemption:output_type -> proto.hummingbird.v1.DelegateRedemptionResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_hummingbird_v1_redemption_proto_init() }
func file_proto_hummingbird_v1_redemption_proto_init() {
	if File_proto_hummingbird_v1_redemption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hummingbird_v1_redemption_proto_rawDesc), len(file_proto_hummingbird_v1_redemption_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hummingbird_v1_redemption_proto_goTypes,
		DependencyIndexes: file_proto_hummingbird_v1_redemption_proto_depIdxs,
		MessageInfos:      file_proto_hummingbird_v1_redemption_proto_msgTypes,
	}.Build()
	File_proto_hummingbird_v1_redemption_proto = out.File
	file_proto_hummingbird_v1_redemption_proto_goTypes = nil
	file_proto_hummingbird_v1_redemption_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RedemptionServiceClient is the client API for RedemptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RedemptionServiceClient interface {
	RedeemASAsset(ctx context.Context, opts ...grpc.CallOption) (RedemptionService_RedeemASAssetClient, error)
	DelegateRedemption(ctx context.Context, in *DelegateRedemptionRequest, opts ...grpc.CallOption) (*DelegateRedemptionResponse, error)
}

type redemptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedemptionServiceClient(cc grpc.ClientConnInterface) RedemptionServiceClient {
	return &redemptionServiceClient{cc}
}

func (c *redemptionServiceClient) RedeemASAsset(ctx context.Context, opts ...grpc.CallOption) (RedemptionService_RedeemASAssetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RedemptionService_serviceDesc.Streams[0], "/proto.hummingbird.v1.RedemptionService/RedeemASAsset", opts...)
	if err != nil {
		return nil, err
	}
	x := &redemptionServiceRedeemASAssetClient{stream}
	return x, nil
}

type RedemptionService_RedeemASAssetClient interface {
	Send(*RedeemAssetFromASResponse) error
	Recv() (*RedeemAssetFromASRequest, error)
	grpc.ClientStream
}

type redemptionServiceRedeemASAssetClient struct {
	grpc.ClientStream
}

func (x *redemptionServiceRedeemASAssetClient) Send(m *RedeemAssetFromASResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *redemptionServiceRedeemASAssetClient) Recv() (*RedeemAssetFromASRequest, error) {
	m := new(RedeemAssetFromASRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *redemptionServiceClient) DelegateRedemption(ctx context.Context, in *DelegateRedemptionRequest, opts ...grpc.CallOption) (*DelegateRedemptionResponse, error) {
	out := new(DelegateRedemptionResponse)
	err := c.cc.Invoke(ctx, "/proto.hummingbird.v1.RedemptionService/DelegateRedemption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedemptionServiceServer is the server API for RedemptionService service.
type RedemptionServiceServer interface {
	RedeemASAsset(RedemptionService_RedeemASAssetServer) error
	DelegateRedemption(context.Context, *DelegateRedemptionRequest) (*DelegateRedemptionResponse, error)
}

// UnimplementedRedemptionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRedemptionServiceServer struct {
}

func (*UnimplementedRedemptionServiceServer) RedeemASAsset(RedemptionService_RedeemASAssetServer) error {
	return status.Errorf(codes.Unimplemented, "method RedeemASAsset not implemented")
}
func (*UnimplementedRedemptionServiceServer) DelegateRedemption(context.Context, *DelegateRedemptionRequest) (*DelegateRedemptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateRedemption not implemented")
}

func RegisterRedemptionServiceServer(s *grpc.Server, srv RedemptionServiceServer) {
	s.RegisterService(&_RedemptionService_serviceDesc, srv)
}

func _RedemptionService_RedeemASAsset_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RedemptionServiceServer).RedeemASAsset(&redemptionServiceRedeemASAssetServer{stream})
}

type RedemptionService_RedeemASAssetServer interface {
	Send(*RedeemAssetFromASRequest) error
	Recv() (*RedeemAssetFromASResponse, error)
	grpc.ServerStream
}

type redemptionServiceRedeemASAssetServer struct {
	grpc.ServerStream
}

func (x *redemptionServiceRedeemASAssetServer) Send(m *RedeemAssetFromASRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *redemptionServiceRedeemASAssetServer) Recv() (*RedeemAssetFromASResponse, error) {
	m := new(RedeemAssetFromASResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RedemptionService_DelegateRedemption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelegateRedemptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedemptionServiceServer).DelegateRedemption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.hummingbird.v1.RedemptionService/DelegateRedemption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedemptionServiceServer).DelegateRedemption(ctx, req.(*DelegateRedemptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RedemptionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.hummingbird.v1.RedemptionService",
	HandlerType: (*RedemptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DelegateRedemption",
			Handler:    _RedemptionService_DelegateRedemption_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RedeemASAsset",
			Handler:       _RedemptionService_RedeemASAsset_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hummingbird/v1/redemption.proto",
}
