load("@rules_go//go:def.bzl", "go_library")
load("//tools:go.bzl", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "bwencoding.go",
        "encodeBandwidthWithLogStart.go",
        "parseBandwidth.go",
    ],
    importpath = "github.com/scionproto/scion/pkg/hummingbird/bwencoding",
    visibility = ["//visibility:public"],
    deps = ["//pkg/slayers/path/hummingbird:go_default_library"],
)

go_test(
    name = "go_default_test",
    srcs = [
        "bwencoding_test.go",
        "parseBandwidth_test.go",
    ],
    embed = [":go_default_library"],
    deps = ["@com_github_stretchr_testify//assert:go_default_library"],
)
