// File generated by ANTLR. DO NOT EDIT.

package pathpolicyconstraints // PathPolicyConstraints
import "github.com/antlr/antlr4/runtime/Go/antlr"

// PathPolicyConstraintsListener is a complete listener for a parse tree produced by PathPolicyConstraintsParser.
type PathPolicyConstraintsListener interface {
	antlr.ParseTreeListener

	// EnterStart is called when entering the start production.
	EnterStart(c *StartContext)

	// EnterIfElse is called when entering the IfElse production.
	EnterIfElse(c *IfElseContext)

	// EnterIf is called when entering the If production.
	EnterIf(c *IfContext)

	// EnterParens is called when entering the Parens production.
	EnterParens(c *ParensContext)

	// EnterExpressionIdentifier is called when entering the ExpressionIdentifier production.
	EnterExpressionIdentifier(c *ExpressionIdentifierContext)

	// EnterExpressionConcat is called when entering the ExpressionConcat production.
	EnterExpressionConcat(c *ExpressionConcatContext)

	// EnterExpressionQuery is called when entering the ExpressionQuery production.
	EnterExpressionQuery(c *ExpressionQueryContext)

	// EnterIdentifier is called when entering the identifier production.
	EnterIdentifier(c *IdentifierContext)

	// EnterWildcardISD is called when entering the WildcardISD production.
	EnterWildcardISD(c *WildcardISDContext)

	// EnterISD is called when entering the ISD production.
	EnterISD(c *ISDContext)

	// EnterWildcardAS is called when entering the WildcardAS production.
	EnterWildcardAS(c *WildcardASContext)

	// EnterLegacyAS is called when entering the LegacyAS production.
	EnterLegacyAS(c *LegacyASContext)

	// EnterAS is called when entering the AS production.
	EnterAS(c *ASContext)

	// EnterWildcardIFace is called when entering the WildcardIFace production.
	EnterWildcardIFace(c *WildcardIFaceContext)

	// EnterIFace is called when entering the IFace production.
	EnterIFace(c *IFaceContext)

	// EnterGlobalPolicy is called when entering the GlobalPolicy production.
	EnterGlobalPolicy(c *GlobalPolicyContext)

	// EnterLocalPolicy is called when entering the LocalPolicy production.
	EnterLocalPolicy(c *LocalPolicyContext)

	// EnterWildcardPolicy is called when entering the WildcardPolicy production.
	EnterWildcardPolicy(c *WildcardPolicyContext)

	// EnterReject is called when entering the Reject production.
	EnterReject(c *RejectContext)

	// EnterPolicyIndex is called when entering the PolicyIndex production.
	EnterPolicyIndex(c *PolicyIndexContext)

	// ExitStart is called when exiting the start production.
	ExitStart(c *StartContext)

	// ExitIfElse is called when exiting the IfElse production.
	ExitIfElse(c *IfElseContext)

	// ExitIf is called when exiting the If production.
	ExitIf(c *IfContext)

	// ExitParens is called when exiting the Parens production.
	ExitParens(c *ParensContext)

	// ExitExpressionIdentifier is called when exiting the ExpressionIdentifier production.
	ExitExpressionIdentifier(c *ExpressionIdentifierContext)

	// ExitExpressionConcat is called when exiting the ExpressionConcat production.
	ExitExpressionConcat(c *ExpressionConcatContext)

	// ExitExpressionQuery is called when exiting the ExpressionQuery production.
	ExitExpressionQuery(c *ExpressionQueryContext)

	// ExitIdentifier is called when exiting the identifier production.
	ExitIdentifier(c *IdentifierContext)

	// ExitWildcardISD is called when exiting the WildcardISD production.
	ExitWildcardISD(c *WildcardISDContext)

	// ExitISD is called when exiting the ISD production.
	ExitISD(c *ISDContext)

	// ExitWildcardAS is called when exiting the WildcardAS production.
	ExitWildcardAS(c *WildcardASContext)

	// ExitLegacyAS is called when exiting the LegacyAS production.
	ExitLegacyAS(c *LegacyASContext)

	// ExitAS is called when exiting the AS production.
	ExitAS(c *ASContext)

	// ExitWildcardIFace is called when exiting the WildcardIFace production.
	ExitWildcardIFace(c *WildcardIFaceContext)

	// ExitIFace is called when exiting the IFace production.
	ExitIFace(c *IFaceContext)

	// ExitGlobalPolicy is called when exiting the GlobalPolicy production.
	ExitGlobalPolicy(c *GlobalPolicyContext)

	// ExitLocalPolicy is called when exiting the LocalPolicy production.
	ExitLocalPolicy(c *LocalPolicyContext)

	// ExitWildcardPolicy is called when exiting the WildcardPolicy production.
	ExitWildcardPolicy(c *WildcardPolicyContext)

	// ExitReject is called when exiting the Reject production.
	ExitReject(c *RejectContext)

	// ExitPolicyIndex is called when exiting the PolicyIndex production.
	ExitPolicyIndex(c *PolicyIndexContext)
}
