load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["web.go"],
    importpath = "github.com/scionproto/scion/marketplace/webapp",
    visibility = ["//visibility:public"],
    deps = [
        "//marketplace/db:go_default_library",
        "//marketplace/storage:go_default_library",
        "//pkg/addr:go_default_library",
        "//pkg/log:go_default_library",
        "//pkg/hummingbird/registration:go_default_library",
        "@com_github_golang_jwt_jwt//:go_default_library",
        "@com_github_gorilla_sessions//:go_default_library",
        "@org_golang_x_crypto//bcrypt:go_default_library",
    ],
)
