// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/aa/v1/auth_service.proto

package aaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	aa "github.com/scionproto/scion/pkg/proto/aa"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "anapaya.aa.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceAuthenticateByKeyProcedure is the fully-qualified name of the AuthService's
	// AuthenticateByKey RPC.
	AuthServiceAuthenticateByKeyProcedure = "/anapaya.aa.v1.AuthService/AuthenticateByKey"
)

// AuthServiceClient is a client for the anapaya.aa.v1.AuthService service.
type AuthServiceClient interface {
	AuthenticateByKey(context.Context, *connect.Request[aa.AuthenticateByKeyRequest]) (*connect.Response[aa.AuthenticateByKeyResponse], error)
}

// NewAuthServiceClient constructs a client for the anapaya.aa.v1.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := aa.File_proto_aa_v1_auth_service_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		authenticateByKey: connect.NewClient[aa.AuthenticateByKeyRequest, aa.AuthenticateByKeyResponse](
			httpClient,
			baseURL+AuthServiceAuthenticateByKeyProcedure,
			connect.WithSchema(authServiceMethods.ByName("AuthenticateByKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	authenticateByKey *connect.Client[aa.AuthenticateByKeyRequest, aa.AuthenticateByKeyResponse]
}

// AuthenticateByKey calls anapaya.aa.v1.AuthService.AuthenticateByKey.
func (c *authServiceClient) AuthenticateByKey(ctx context.Context, req *connect.Request[aa.AuthenticateByKeyRequest]) (*connect.Response[aa.AuthenticateByKeyResponse], error) {
	return c.authenticateByKey.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the anapaya.aa.v1.AuthService service.
type AuthServiceHandler interface {
	AuthenticateByKey(context.Context, *connect.Request[aa.AuthenticateByKeyRequest]) (*connect.Response[aa.AuthenticateByKeyResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := aa.File_proto_aa_v1_auth_service_proto.Services().ByName("AuthService").Methods()
	authServiceAuthenticateByKeyHandler := connect.NewUnaryHandler(
		AuthServiceAuthenticateByKeyProcedure,
		svc.AuthenticateByKey,
		connect.WithSchema(authServiceMethods.ByName("AuthenticateByKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/anapaya.aa.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceAuthenticateByKeyProcedure:
			authServiceAuthenticateByKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) AuthenticateByKey(context.Context, *connect.Request[aa.AuthenticateByKeyRequest]) (*connect.Response[aa.AuthenticateByKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("anapaya.aa.v1.AuthService.AuthenticateByKey is not implemented"))
}
