load("//acceptance/common:topogen.bzl", "topogen_test")

# Test end to end integration using the endhost api
topogen_test(
    name = "test_endhost_api",
    src = "test.py",
    args = [
        "--executable=end2end_integration:$(location //tools/end2end_integration)",
    ],
    data = ["//tools/end2end_integration"],
    topo = "//topology:tiny.topo",
)
