load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "account.go",
        "auth.go",
        "config.go",
        "redeem.go",
        "redemption_service.go",
        "service.go",
        "trust_db_wrapper.go",
    ],
    importpath = "github.com/scionproto/scion/marketplace",
    visibility = ["//visibility:public"],
    deps = [
        "//marketplace/db:go_default_library",
        "//marketplace/storage:go_default_library",
        "//pkg/addr:go_default_library",
        "//pkg/hummingbird/registration:go_default_library",
        "//pkg/log:go_default_library",
        "//pkg/private/serrors:go_default_library",
        "//pkg/proto/hummingbird:go_default_library",
        "//pkg/scrypto/cppki:go_default_library",
        "//pkg/slayers/path/hummingbird:go_default_library",
        "//private/config:go_default_library",
        "//private/env:go_default_library",
        "//private/storage:go_default_library",
        "//private/storage/trust:go_default_library",
        "//private/trust:go_default_library",
        "@com_connectrpc_connect//:go_default_library",
        "@com_github_golang_jwt_jwt//:go_default_library",
        "@org_golang_google_protobuf//types/known/timestamppb:go_default_library",
        "@org_golang_x_crypto//bcrypt:go_default_library",
    ],
)
