apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:${PROMETHEUS_PORT}
    isDefault: true
    editable: true
