// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/aa/v1/auth.proto

package aa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateByKeyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApiKey            string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	DeviceId          string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RequestedValidity int32                  `protobuf:"varint,3,opt,name=requested_validity,json=requestedValidity,proto3" json:"requested_validity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthenticateByKeyRequest) Reset() {
	*x = AuthenticateByKeyRequest{}
	mi := &file_proto_aa_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateByKeyRequest) ProtoMessage() {}

func (x *AuthenticateByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aa_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateByKeyRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateByKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_aa_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateByKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AuthenticateByKeyRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthenticateByKeyRequest) GetRequestedValidity() int32 {
	if x != nil {
		return x.RequestedValidity
	}
	return 0
}

type Metadata struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EndhostApiDiscoveryUrl *string                `protobuf:"bytes,1,opt,name=endhost_api_discovery_url,json=endhostApiDiscoveryUrl,proto3,oneof" json:"endhost_api_discovery_url,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_aa_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aa_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_aa_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetEndhostApiDiscoveryUrl() string {
	if x != nil && x.EndhostApiDiscoveryUrl != nil {
		return *x.EndhostApiDiscoveryUrl
	}
	return ""
}

type AuthenticateByKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapToken     string                 `protobuf:"bytes,1,opt,name=snap_token,json=snapToken,proto3" json:"snap_token,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateByKeyResponse) Reset() {
	*x = AuthenticateByKeyResponse{}
	mi := &file_proto_aa_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateByKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateByKeyResponse) ProtoMessage() {}

func (x *AuthenticateByKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aa_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateByKeyResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateByKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_aa_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateByKeyResponse) GetSnapToken() string {
	if x != nil {
		return x.SnapToken
	}
	return ""
}

func (x *AuthenticateByKeyResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_aa_v1_auth_proto protoreflect.FileDescriptor

const file_proto_aa_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16proto/aa/v1/auth.proto\x12\ranapaya.aa.v1\"\x7f\n" +
	"\x18AuthenticateByKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12-\n" +
	"\x12requested_validity\x18\x03 \x01(\x05R\x11requestedValidity\"h\n" +
	"\bMetadata\x12>\n" +
	"\x19endhost_api_discovery_url\x18\x01 \x01(\tH\x00R\x16endhostApiDiscoveryUrl\x88\x01\x01B\x1c\n" +
	"\x1a_endhost_api_discovery_url\"\x81\x01\n" +
	"\x19AuthenticateByKeyResponse\x12\x1d\n" +
	"\n" +
	"snap_token\x18\x01 \x01(\tR\tsnapToken\x128\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.anapaya.aa.v1.MetadataH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata2u\n" +
	"\vAuthService\x12f\n" +
	"\x11AuthenticateByKey\x12'.anapaya.aa.v1.AuthenticateByKeyRequest\x1a(.anapaya.aa.v1.AuthenticateByKeyResponseb\x06proto3"

var (
	file_proto_aa_v1_auth_proto_rawDescOnce sync.Once
	file_proto_aa_v1_auth_proto_rawDescData []byte
)

func file_proto_aa_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_aa_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_aa_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aa_v1_auth_proto_rawDesc), len(file_proto_aa_v1_auth_proto_rawDesc)))
	})
	return file_proto_aa_v1_auth_proto_rawDescData
}

var file_proto_aa_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_aa_v1_auth_proto_goTypes = []any{
	(*AuthenticateByKeyRequest)(nil),  // 0: anapaya.aa.v1.AuthenticateByKeyRequest
	(*Metadata)(nil),                  // 1: anapaya.aa.v1.Metadata
	(*AuthenticateByKeyResponse)(nil), // 2: anapaya.aa.v1.AuthenticateByKeyResponse
}
var file_proto_aa_v1_auth_proto_depIdxs = []int32{
	1, // 0: anapaya.aa.v1.AuthenticateByKeyResponse.metadata:type_name -> anapaya.aa.v1.Metadata
	0, // 1: anapaya.aa.v1.AuthService.AuthenticateByKey:input_type -> anapaya.aa.v1.AuthenticateByKeyRequest
	2, // 2: anapaya.aa.v1.AuthService.AuthenticateByKey:output_type -> anapaya.aa.v1.AuthenticateByKeyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_aa_v1_auth_proto_init() }
func file_proto_aa_v1_auth_proto_init() {
	if File_proto_aa_v1_auth_proto != nil {
		return
	}
	file_proto_aa_v1_auth_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_aa_v1_auth_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aa_v1_auth_proto_rawDesc), len(file_proto_aa_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aa_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_aa_v1_auth_proto_depIdxs,
		MessageInfos:      file_proto_aa_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_aa_v1_auth_proto = out.File
	file_proto_aa_v1_auth_proto_goTypes = nil
	file_proto_aa_v1_auth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	AuthenticateByKey(ctx context.Context, in *AuthenticateByKeyRequest, opts ...grpc.CallOption) (*AuthenticateByKeyResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) AuthenticateByKey(ctx context.Context, in *AuthenticateByKeyRequest, opts ...grpc.CallOption) (*AuthenticateByKeyResponse, error) {
	out := new(AuthenticateByKeyResponse)
	err := c.cc.Invoke(ctx, "/anapaya.aa.v1.AuthService/AuthenticateByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	AuthenticateByKey(context.Context, *AuthenticateByKeyRequest) (*AuthenticateByKeyResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) AuthenticateByKey(context.Context, *AuthenticateByKeyRequest) (*AuthenticateByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateByKey not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_AuthenticateByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AuthenticateByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anapaya.aa.v1.AuthService/AuthenticateByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AuthenticateByKey(ctx, req.(*AuthenticateByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "anapaya.aa.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateByKey",
			Handler:    _AuthService_AuthenticateByKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aa/v1/auth.proto",
}
