// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/hummingbird/v1/account.proto

package hummingbirdconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	hummingbird "github.com/scionproto/scion/pkg/proto/hummingbird"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountServiceName is the fully-qualified name of the AccountService service.
	AccountServiceName = "proto.hummingbird.v1.AccountService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountServiceIssueJWTProcedure is the fully-qualified name of the AccountService's IssueJWT RPC.
	AccountServiceIssueJWTProcedure = "/proto.hummingbird.v1.AccountService/IssueJWT"
	// AccountServiceResetJWTProcedure is the fully-qualified name of the AccountService's ResetJWT RPC.
	AccountServiceResetJWTProcedure = "/proto.hummingbird.v1.AccountService/ResetJWT"
)

// AccountServiceClient is a client for the proto.hummingbird.v1.AccountService service.
type AccountServiceClient interface {
	IssueJWT(context.Context, *connect.Request[hummingbird.JWTIssuanceRequest]) (*connect.Response[hummingbird.JWTIssuanceResponse], error)
	ResetJWT(context.Context, *connect.Request[hummingbird.JWTResetRequest]) (*connect.Response[hummingbird.JWTResetResponse], error)
}

// NewAccountServiceClient constructs a client for the proto.hummingbird.v1.AccountService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accountServiceMethods := hummingbird.File_proto_hummingbird_v1_account_proto.Services().ByName("AccountService").Methods()
	return &accountServiceClient{
		issueJWT: connect.NewClient[hummingbird.JWTIssuanceRequest, hummingbird.JWTIssuanceResponse](
			httpClient,
			baseURL+AccountServiceIssueJWTProcedure,
			connect.WithSchema(accountServiceMethods.ByName("IssueJWT")),
			connect.WithClientOptions(opts...),
		),
		resetJWT: connect.NewClient[hummingbird.JWTResetRequest, hummingbird.JWTResetResponse](
			httpClient,
			baseURL+AccountServiceResetJWTProcedure,
			connect.WithSchema(accountServiceMethods.ByName("ResetJWT")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountServiceClient implements AccountServiceClient.
type accountServiceClient struct {
	issueJWT *connect.Client[hummingbird.JWTIssuanceRequest, hummingbird.JWTIssuanceResponse]
	resetJWT *connect.Client[hummingbird.JWTResetRequest, hummingbird.JWTResetResponse]
}

// IssueJWT calls proto.hummingbird.v1.AccountService.IssueJWT.
func (c *accountServiceClient) IssueJWT(ctx context.Context, req *connect.Request[hummingbird.JWTIssuanceRequest]) (*connect.Response[hummingbird.JWTIssuanceResponse], error) {
	return c.issueJWT.CallUnary(ctx, req)
}

// ResetJWT calls proto.hummingbird.v1.AccountService.ResetJWT.
func (c *accountServiceClient) ResetJWT(ctx context.Context, req *connect.Request[hummingbird.JWTResetRequest]) (*connect.Response[hummingbird.JWTResetResponse], error) {
	return c.resetJWT.CallUnary(ctx, req)
}

// AccountServiceHandler is an implementation of the proto.hummingbird.v1.AccountService service.
type AccountServiceHandler interface {
	IssueJWT(context.Context, *connect.Request[hummingbird.JWTIssuanceRequest]) (*connect.Response[hummingbird.JWTIssuanceResponse], error)
	ResetJWT(context.Context, *connect.Request[hummingbird.JWTResetRequest]) (*connect.Response[hummingbird.JWTResetResponse], error)
}

// NewAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountServiceHandler(svc AccountServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountServiceMethods := hummingbird.File_proto_hummingbird_v1_account_proto.Services().ByName("AccountService").Methods()
	accountServiceIssueJWTHandler := connect.NewUnaryHandler(
		AccountServiceIssueJWTProcedure,
		svc.IssueJWT,
		connect.WithSchema(accountServiceMethods.ByName("IssueJWT")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceResetJWTHandler := connect.NewUnaryHandler(
		AccountServiceResetJWTProcedure,
		svc.ResetJWT,
		connect.WithSchema(accountServiceMethods.ByName("ResetJWT")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.hummingbird.v1.AccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountServiceIssueJWTProcedure:
			accountServiceIssueJWTHandler.ServeHTTP(w, r)
		case AccountServiceResetJWTProcedure:
			accountServiceResetJWTHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountServiceHandler struct{}

func (UnimplementedAccountServiceHandler) IssueJWT(context.Context, *connect.Request[hummingbird.JWTIssuanceRequest]) (*connect.Response[hummingbird.JWTIssuanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.AccountService.IssueJWT is not implemented"))
}

func (UnimplementedAccountServiceHandler) ResetJWT(context.Context, *connect.Request[hummingbird.JWTResetRequest]) (*connect.Response[hummingbird.JWTResetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.AccountService.ResetJWT is not implemented"))
}
