// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/hummingbird/v1/marketplace.proto

package hummingbirdconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	hummingbird "github.com/scionproto/scion/pkg/proto/hummingbird"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MarketplaceServiceName is the fully-qualified name of the MarketplaceService service.
	MarketplaceServiceName = "proto.hummingbird.v1.MarketplaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MarketplaceServiceInfoProcedure is the fully-qualified name of the MarketplaceService's Info RPC.
	MarketplaceServiceInfoProcedure = "/proto.hummingbird.v1.MarketplaceService/Info"
	// MarketplaceServicePublishAssetProcedure is the fully-qualified name of the MarketplaceService's
	// PublishAsset RPC.
	MarketplaceServicePublishAssetProcedure = "/proto.hummingbird.v1.MarketplaceService/PublishAsset"
	// MarketplaceServiceSearchAssetsProcedure is the fully-qualified name of the MarketplaceService's
	// SearchAssets RPC.
	MarketplaceServiceSearchAssetsProcedure = "/proto.hummingbird.v1.MarketplaceService/SearchAssets"
	// MarketplaceServiceBuyAssetsProcedure is the fully-qualified name of the MarketplaceService's
	// BuyAssets RPC.
	MarketplaceServiceBuyAssetsProcedure = "/proto.hummingbird.v1.MarketplaceService/BuyAssets"
	// MarketplaceServiceRedeemAssetProcedure is the fully-qualified name of the MarketplaceService's
	// RedeemAsset RPC.
	MarketplaceServiceRedeemAssetProcedure = "/proto.hummingbird.v1.MarketplaceService/RedeemAsset"
	// MarketplaceServiceFetchReservationsProcedure is the fully-qualified name of the
	// MarketplaceService's FetchReservations RPC.
	MarketplaceServiceFetchReservationsProcedure = "/proto.hummingbird.v1.MarketplaceService/FetchReservations"
	// MarketplaceServiceSplitAssetProcedure is the fully-qualified name of the MarketplaceService's
	// SplitAsset RPC.
	MarketplaceServiceSplitAssetProcedure = "/proto.hummingbird.v1.MarketplaceService/SplitAsset"
	// MarketplaceServiceCombineAssetsProcedure is the fully-qualified name of the MarketplaceService's
	// CombineAssets RPC.
	MarketplaceServiceCombineAssetsProcedure = "/proto.hummingbird.v1.MarketplaceService/CombineAssets"
)

// MarketplaceServiceClient is a client for the proto.hummingbird.v1.MarketplaceService service.
type MarketplaceServiceClient interface {
	Info(context.Context, *connect.Request[hummingbird.MarketplaceInfoRequest]) (*connect.Response[hummingbird.MarketplaceInfoResponse], error)
	PublishAsset(context.Context, *connect.Request[hummingbird.PublishAssetRequest]) (*connect.Response[hummingbird.PublishAssetResponse], error)
	SearchAssets(context.Context, *connect.Request[hummingbird.SearchAssetsRequest]) (*connect.Response[hummingbird.SearchAssetsResponse], error)
	BuyAssets(context.Context, *connect.Request[hummingbird.BuyAssetsRequest]) (*connect.Response[hummingbird.BuyAssetsResponse], error)
	RedeemAsset(context.Context, *connect.Request[hummingbird.RedeemAssetRequest]) (*connect.Response[hummingbird.RedeemAssetResponse], error)
	FetchReservations(context.Context, *connect.Request[hummingbird.FetchReservationsRequest]) (*connect.Response[hummingbird.FetchReservationsResponse], error)
	SplitAsset(context.Context, *connect.Request[hummingbird.SplitAssetRequest]) (*connect.Response[hummingbird.SplitAssetResponse], error)
	CombineAssets(context.Context, *connect.Request[hummingbird.CombineAssetRequest]) (*connect.Response[hummingbird.CombineAssetResponse], error)
}

// NewMarketplaceServiceClient constructs a client for the proto.hummingbird.v1.MarketplaceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMarketplaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MarketplaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	marketplaceServiceMethods := hummingbird.File_proto_hummingbird_v1_marketplace_proto.Services().ByName("MarketplaceService").Methods()
	return &marketplaceServiceClient{
		info: connect.NewClient[hummingbird.MarketplaceInfoRequest, hummingbird.MarketplaceInfoResponse](
			httpClient,
			baseURL+MarketplaceServiceInfoProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
		publishAsset: connect.NewClient[hummingbird.PublishAssetRequest, hummingbird.PublishAssetResponse](
			httpClient,
			baseURL+MarketplaceServicePublishAssetProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("PublishAsset")),
			connect.WithClientOptions(opts...),
		),
		searchAssets: connect.NewClient[hummingbird.SearchAssetsRequest, hummingbird.SearchAssetsResponse](
			httpClient,
			baseURL+MarketplaceServiceSearchAssetsProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("SearchAssets")),
			connect.WithClientOptions(opts...),
		),
		buyAssets: connect.NewClient[hummingbird.BuyAssetsRequest, hummingbird.BuyAssetsResponse](
			httpClient,
			baseURL+MarketplaceServiceBuyAssetsProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("BuyAssets")),
			connect.WithClientOptions(opts...),
		),
		redeemAsset: connect.NewClient[hummingbird.RedeemAssetRequest, hummingbird.RedeemAssetResponse](
			httpClient,
			baseURL+MarketplaceServiceRedeemAssetProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("RedeemAsset")),
			connect.WithClientOptions(opts...),
		),
		fetchReservations: connect.NewClient[hummingbird.FetchReservationsRequest, hummingbird.FetchReservationsResponse](
			httpClient,
			baseURL+MarketplaceServiceFetchReservationsProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("FetchReservations")),
			connect.WithClientOptions(opts...),
		),
		splitAsset: connect.NewClient[hummingbird.SplitAssetRequest, hummingbird.SplitAssetResponse](
			httpClient,
			baseURL+MarketplaceServiceSplitAssetProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("SplitAsset")),
			connect.WithClientOptions(opts...),
		),
		combineAssets: connect.NewClient[hummingbird.CombineAssetRequest, hummingbird.CombineAssetResponse](
			httpClient,
			baseURL+MarketplaceServiceCombineAssetsProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("CombineAssets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// marketplaceServiceClient implements MarketplaceServiceClient.
type marketplaceServiceClient struct {
	info              *connect.Client[hummingbird.MarketplaceInfoRequest, hummingbird.MarketplaceInfoResponse]
	publishAsset      *connect.Client[hummingbird.PublishAssetRequest, hummingbird.PublishAssetResponse]
	searchAssets      *connect.Client[hummingbird.SearchAssetsRequest, hummingbird.SearchAssetsResponse]
	buyAssets         *connect.Client[hummingbird.BuyAssetsRequest, hummingbird.BuyAssetsResponse]
	redeemAsset       *connect.Client[hummingbird.RedeemAssetRequest, hummingbird.RedeemAssetResponse]
	fetchReservations *connect.Client[hummingbird.FetchReservationsRequest, hummingbird.FetchReservationsResponse]
	splitAsset        *connect.Client[hummingbird.SplitAssetRequest, hummingbird.SplitAssetResponse]
	combineAssets     *connect.Client[hummingbird.CombineAssetRequest, hummingbird.CombineAssetResponse]
}

// Info calls proto.hummingbird.v1.MarketplaceService.Info.
func (c *marketplaceServiceClient) Info(ctx context.Context, req *connect.Request[hummingbird.MarketplaceInfoRequest]) (*connect.Response[hummingbird.MarketplaceInfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// PublishAsset calls proto.hummingbird.v1.MarketplaceService.PublishAsset.
func (c *marketplaceServiceClient) PublishAsset(ctx context.Context, req *connect.Request[hummingbird.PublishAssetRequest]) (*connect.Response[hummingbird.PublishAssetResponse], error) {
	return c.publishAsset.CallUnary(ctx, req)
}

// SearchAssets calls proto.hummingbird.v1.MarketplaceService.SearchAssets.
func (c *marketplaceServiceClient) SearchAssets(ctx context.Context, req *connect.Request[hummingbird.SearchAssetsRequest]) (*connect.Response[hummingbird.SearchAssetsResponse], error) {
	return c.searchAssets.CallUnary(ctx, req)
}

// BuyAssets calls proto.hummingbird.v1.MarketplaceService.BuyAssets.
func (c *marketplaceServiceClient) BuyAssets(ctx context.Context, req *connect.Request[hummingbird.BuyAssetsRequest]) (*connect.Response[hummingbird.BuyAssetsResponse], error) {
	return c.buyAssets.CallUnary(ctx, req)
}

// RedeemAsset calls proto.hummingbird.v1.MarketplaceService.RedeemAsset.
func (c *marketplaceServiceClient) RedeemAsset(ctx context.Context, req *connect.Request[hummingbird.RedeemAssetRequest]) (*connect.Response[hummingbird.RedeemAssetResponse], error) {
	return c.redeemAsset.CallUnary(ctx, req)
}

// FetchReservations calls proto.hummingbird.v1.MarketplaceService.FetchReservations.
func (c *marketplaceServiceClient) FetchReservations(ctx context.Context, req *connect.Request[hummingbird.FetchReservationsRequest]) (*connect.Response[hummingbird.FetchReservationsResponse], error) {
	return c.fetchReservations.CallUnary(ctx, req)
}

// SplitAsset calls proto.hummingbird.v1.MarketplaceService.SplitAsset.
func (c *marketplaceServiceClient) SplitAsset(ctx context.Context, req *connect.Request[hummingbird.SplitAssetRequest]) (*connect.Response[hummingbird.SplitAssetResponse], error) {
	return c.splitAsset.CallUnary(ctx, req)
}

// CombineAssets calls proto.hummingbird.v1.MarketplaceService.CombineAssets.
func (c *marketplaceServiceClient) CombineAssets(ctx context.Context, req *connect.Request[hummingbird.CombineAssetRequest]) (*connect.Response[hummingbird.CombineAssetResponse], error) {
	return c.combineAssets.CallUnary(ctx, req)
}

// MarketplaceServiceHandler is an implementation of the proto.hummingbird.v1.MarketplaceService
// service.
type MarketplaceServiceHandler interface {
	Info(context.Context, *connect.Request[hummingbird.MarketplaceInfoRequest]) (*connect.Response[hummingbird.MarketplaceInfoResponse], error)
	PublishAsset(context.Context, *connect.Request[hummingbird.PublishAssetRequest]) (*connect.Response[hummingbird.PublishAssetResponse], error)
	SearchAssets(context.Context, *connect.Request[hummingbird.SearchAssetsRequest]) (*connect.Response[hummingbird.SearchAssetsResponse], error)
	BuyAssets(context.Context, *connect.Request[hummingbird.BuyAssetsRequest]) (*connect.Response[hummingbird.BuyAssetsResponse], error)
	RedeemAsset(context.Context, *connect.Request[hummingbird.RedeemAssetRequest]) (*connect.Response[hummingbird.RedeemAssetResponse], error)
	FetchReservations(context.Context, *connect.Request[hummingbird.FetchReservationsRequest]) (*connect.Response[hummingbird.FetchReservationsResponse], error)
	SplitAsset(context.Context, *connect.Request[hummingbird.SplitAssetRequest]) (*connect.Response[hummingbird.SplitAssetResponse], error)
	CombineAssets(context.Context, *connect.Request[hummingbird.CombineAssetRequest]) (*connect.Response[hummingbird.CombineAssetResponse], error)
}

// NewMarketplaceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMarketplaceServiceHandler(svc MarketplaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	marketplaceServiceMethods := hummingbird.File_proto_hummingbird_v1_marketplace_proto.Services().ByName("MarketplaceService").Methods()
	marketplaceServiceInfoHandler := connect.NewUnaryHandler(
		MarketplaceServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(marketplaceServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServicePublishAssetHandler := connect.NewUnaryHandler(
		MarketplaceServicePublishAssetProcedure,
		svc.PublishAsset,
		connect.WithSchema(marketplaceServiceMethods.ByName("PublishAsset")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceSearchAssetsHandler := connect.NewUnaryHandler(
		MarketplaceServiceSearchAssetsProcedure,
		svc.SearchAssets,
		connect.WithSchema(marketplaceServiceMethods.ByName("SearchAssets")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceBuyAssetsHandler := connect.NewUnaryHandler(
		MarketplaceServiceBuyAssetsProcedure,
		svc.BuyAssets,
		connect.WithSchema(marketplaceServiceMethods.ByName("BuyAssets")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceRedeemAssetHandler := connect.NewUnaryHandler(
		MarketplaceServiceRedeemAssetProcedure,
		svc.RedeemAsset,
		connect.WithSchema(marketplaceServiceMethods.ByName("RedeemAsset")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceFetchReservationsHandler := connect.NewUnaryHandler(
		MarketplaceServiceFetchReservationsProcedure,
		svc.FetchReservations,
		connect.WithSchema(marketplaceServiceMethods.ByName("FetchReservations")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceSplitAssetHandler := connect.NewUnaryHandler(
		MarketplaceServiceSplitAssetProcedure,
		svc.SplitAsset,
		connect.WithSchema(marketplaceServiceMethods.ByName("SplitAsset")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceCombineAssetsHandler := connect.NewUnaryHandler(
		MarketplaceServiceCombineAssetsProcedure,
		svc.CombineAssets,
		connect.WithSchema(marketplaceServiceMethods.ByName("CombineAssets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.hummingbird.v1.MarketplaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MarketplaceServiceInfoProcedure:
			marketplaceServiceInfoHandler.ServeHTTP(w, r)
		case MarketplaceServicePublishAssetProcedure:
			marketplaceServicePublishAssetHandler.ServeHTTP(w, r)
		case MarketplaceServiceSearchAssetsProcedure:
			marketplaceServiceSearchAssetsHandler.ServeHTTP(w, r)
		case MarketplaceServiceBuyAssetsProcedure:
			marketplaceServiceBuyAssetsHandler.ServeHTTP(w, r)
		case MarketplaceServiceRedeemAssetProcedure:
			marketplaceServiceRedeemAssetHandler.ServeHTTP(w, r)
		case MarketplaceServiceFetchReservationsProcedure:
			marketplaceServiceFetchReservationsHandler.ServeHTTP(w, r)
		case MarketplaceServiceSplitAssetProcedure:
			marketplaceServiceSplitAssetHandler.ServeHTTP(w, r)
		case MarketplaceServiceCombineAssetsProcedure:
			marketplaceServiceCombineAssetsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMarketplaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMarketplaceServiceHandler struct{}

func (UnimplementedMarketplaceServiceHandler) Info(context.Context, *connect.Request[hummingbird.MarketplaceInfoRequest]) (*connect.Response[hummingbird.MarketplaceInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.MarketplaceService.Info is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) PublishAsset(context.Context, *connect.Request[hummingbird.PublishAssetRequest]) (*connect.Response[hummingbird.PublishAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.MarketplaceService.PublishAsset is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) SearchAssets(context.Context, *connect.Request[hummingbird.SearchAssetsRequest]) (*connect.Response[hummingbird.SearchAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.MarketplaceService.SearchAssets is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) BuyAssets(context.Context, *connect.Request[hummingbird.BuyAssetsRequest]) (*connect.Response[hummingbird.BuyAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.MarketplaceService.BuyAssets is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) RedeemAsset(context.Context, *connect.Request[hummingbird.RedeemAssetRequest]) (*connect.Response[hummingbird.RedeemAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.MarketplaceService.RedeemAsset is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) FetchReservations(context.Context, *connect.Request[hummingbird.FetchReservationsRequest]) (*connect.Response[hummingbird.FetchReservationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.MarketplaceService.FetchReservations is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) SplitAsset(context.Context, *connect.Request[hummingbird.SplitAssetRequest]) (*connect.Response[hummingbird.SplitAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.MarketplaceService.SplitAsset is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) CombineAssets(context.Context, *connect.Request[hummingbird.CombineAssetRequest]) (*connect.Response[hummingbird.CombineAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.hummingbird.v1.MarketplaceService.CombineAssets is not implemented"))
}
