load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

go_proto_library(
    name = "go_default_library",
    compiler = "@io_bazel_rules_go//proto:go_grpc",
    importpath = "github.com/scionproto/scion/pkg/proto/proof_of_forwarding",
    proto = "//proto/proof_of_forwarding/v1:proof_of_forwarding",
    visibility = ["//visibility:public"],
)
