// Copyright 2025 ETH Zurich
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


syntax = "proto3";

option go_package = "github.com/scionproto/scion/pkg/proto/proof_of_forwarding";

package proto.proof_of_forwarding.v1;

import "google/protobuf/timestamp.proto";

service MonitorService {
    rpc Collect(CollectRequest) returns (CollectResponse) {}
}

message CollectRequest {
    uint32 frame_id = 1;
}

message CollectResponseEntry {
    uint32 index = 1;
    uint32 ingress = 2;
    optional uint32 egress = 3;
    bytes bucket = 4;
    uint32 counter = 5;
    bool is_ingress = 6;
}

message CollectResponse {
    repeated CollectResponseEntry entries = 1;
}

service BucketStore {
    rpc Query(QueryRequest) returns (QueryResponse) {}
    rpc ReportDrop(DropRequest) returns (DropResponse) {}
}

message DropRequest {
    google.protobuf.Timestamp send_time = 1;
    uint32 ingress = 2;
    optional uint32 egress = 3;
    bytes bucket = 4;
}

message DropResponse {
    bool success = 1;
}

message QueryRequest {
    google.protobuf.Timestamp send_time = 1;
}

message QueryResponse {
    uint32 index = 1;
    repeated QueryResponseEntry entries = 2;
}

message QueryResponseEntry {
    uint32 ingress = 1;
    optional uint32 egress = 2;
    bytes bucket = 3;
    uint32 counter = 4;
    bool is_ingress = 5;
}