load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "endhost",
    srcs = [
        "path.proto",
        "trust.proto",
        "underlay.proto",
        "drkey.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//proto/control_plane/v1:control_plane",
        "//proto/drkey/v1:drkey",
        "@protobuf//:timestamp_proto",
    ],
)
