// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/snap/v1/snap.proto

package snap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSnapDataPlaneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapDataPlaneRequest) Reset() {
	*x = GetSnapDataPlaneRequest{}
	mi := &file_proto_snap_v1_snap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapDataPlaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapDataPlaneRequest) ProtoMessage() {}

func (x *GetSnapDataPlaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snap_v1_snap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapDataPlaneRequest.ProtoReflect.Descriptor instead.
func (*GetSnapDataPlaneRequest) Descriptor() ([]byte, []int) {
	return file_proto_snap_v1_snap_proto_rawDescGZIP(), []int{0}
}

type GetSnapDataPlaneResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Address               string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SnapTunControlAddress *string                `protobuf:"bytes,2,opt,name=snap_tun_control_address,json=snapTunControlAddress,proto3,oneof" json:"snap_tun_control_address,omitempty"`
	SnapStaticX25519      []byte                 `protobuf:"bytes,3,opt,name=snap_static_x25519,json=snapStaticX25519,proto3,oneof" json:"snap_static_x25519,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSnapDataPlaneResponse) Reset() {
	*x = GetSnapDataPlaneResponse{}
	mi := &file_proto_snap_v1_snap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapDataPlaneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapDataPlaneResponse) ProtoMessage() {}

func (x *GetSnapDataPlaneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snap_v1_snap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapDataPlaneResponse.ProtoReflect.Descriptor instead.
func (*GetSnapDataPlaneResponse) Descriptor() ([]byte, []int) {
	return file_proto_snap_v1_snap_proto_rawDescGZIP(), []int{1}
}

func (x *GetSnapDataPlaneResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetSnapDataPlaneResponse) GetSnapTunControlAddress() string {
	if x != nil && x.SnapTunControlAddress != nil {
		return *x.SnapTunControlAddress
	}
	return ""
}

func (x *GetSnapDataPlaneResponse) GetSnapStaticX25519() []byte {
	if x != nil {
		return x.SnapStaticX25519
	}
	return nil
}

type RegisterSnapTunIdentityRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	InitiatorStaticX25519 []byte                 `protobuf:"bytes,1,opt,name=initiator_static_x25519,json=initiatorStaticX25519,proto3" json:"initiator_static_x25519,omitempty"`
	PskShare              []byte                 `protobuf:"bytes,2,opt,name=psk_share,json=pskShare,proto3" json:"psk_share,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterSnapTunIdentityRequest) Reset() {
	*x = RegisterSnapTunIdentityRequest{}
	mi := &file_proto_snap_v1_snap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSnapTunIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSnapTunIdentityRequest) ProtoMessage() {}

func (x *RegisterSnapTunIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snap_v1_snap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSnapTunIdentityRequest.ProtoReflect.Descriptor instead.
func (*RegisterSnapTunIdentityRequest) Descriptor() ([]byte, []int) {
	return file_proto_snap_v1_snap_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSnapTunIdentityRequest) GetInitiatorStaticX25519() []byte {
	if x != nil {
		return x.InitiatorStaticX25519
	}
	return nil
}

func (x *RegisterSnapTunIdentityRequest) GetPskShare() []byte {
	if x != nil {
		return x.PskShare
	}
	return nil
}

type RegisterSnapTunIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PskShare      []byte                 `protobuf:"bytes,1,opt,name=psk_share,json=pskShare,proto3" json:"psk_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSnapTunIdentityResponse) Reset() {
	*x = RegisterSnapTunIdentityResponse{}
	mi := &file_proto_snap_v1_snap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSnapTunIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSnapTunIdentityResponse) ProtoMessage() {}

func (x *RegisterSnapTunIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snap_v1_snap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSnapTunIdentityResponse.ProtoReflect.Descriptor instead.
func (*RegisterSnapTunIdentityResponse) Descriptor() ([]byte, []int) {
	return file_proto_snap_v1_snap_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterSnapTunIdentityResponse) GetPskShare() []byte {
	if x != nil {
		return x.PskShare
	}
	return nil
}

var File_proto_snap_v1_snap_proto protoreflect.FileDescriptor

const file_proto_snap_v1_snap_proto_rawDesc = "" +
	"\n" +
	"\x18proto/snap/v1/snap.proto\x12\x0fanapaya.snap.v1\"\x19\n" +
	"\x17GetSnapDataPlaneRequest\"\xd9\x01\n" +
	"\x18GetSnapDataPlaneResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12<\n" +
	"\x18snap_tun_control_address\x18\x02 \x01(\tH\x00R\x15snapTunControlAddress\x88\x01\x01\x121\n" +
	"\x12snap_static_x25519\x18\x03 \x01(\fH\x01R\x10snapStaticX25519\x88\x01\x01B\x1b\n" +
	"\x19_snap_tun_control_addressB\x15\n" +
	"\x13_snap_static_x25519\"u\n" +
	"\x1eRegisterSnapTunIdentityRequest\x126\n" +
	"\x17initiator_static_x25519\x18\x01 \x01(\fR\x15initiatorStaticX25519\x12\x1b\n" +
	"\tpsk_share\x18\x02 \x01(\fR\bpskShare\">\n" +
	"\x1fRegisterSnapTunIdentityResponse\x12\x1b\n" +
	"\tpsk_share\x18\x01 \x01(\fR\bpskShare2\xff\x01\n" +
	"\vSnapControl\x12p\n" +
	"\x17GetSnapDataPlaneAddress\x12(.anapaya.snap.v1.GetSnapDataPlaneRequest\x1a).anapaya.snap.v1.GetSnapDataPlaneResponse\"\x00\x12~\n" +
	"\x17RegisterSnapTunIdentity\x12/.anapaya.snap.v1.RegisterSnapTunIdentityRequest\x1a0.anapaya.snap.v1.RegisterSnapTunIdentityResponse\"\x00b\x06proto3"

var (
	file_proto_snap_v1_snap_proto_rawDescOnce sync.Once
	file_proto_snap_v1_snap_proto_rawDescData []byte
)

func file_proto_snap_v1_snap_proto_rawDescGZIP() []byte {
	file_proto_snap_v1_snap_proto_rawDescOnce.Do(func() {
		file_proto_snap_v1_snap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_snap_v1_snap_proto_rawDesc), len(file_proto_snap_v1_snap_proto_rawDesc)))
	})
	return file_proto_snap_v1_snap_proto_rawDescData
}

var file_proto_snap_v1_snap_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_snap_v1_snap_proto_goTypes = []any{
	(*GetSnapDataPlaneRequest)(nil),         // 0: anapaya.snap.v1.GetSnapDataPlaneRequest
	(*GetSnapDataPlaneResponse)(nil),        // 1: anapaya.snap.v1.GetSnapDataPlaneResponse
	(*RegisterSnapTunIdentityRequest)(nil),  // 2: anapaya.snap.v1.RegisterSnapTunIdentityRequest
	(*RegisterSnapTunIdentityResponse)(nil), // 3: anapaya.snap.v1.RegisterSnapTunIdentityResponse
}
var file_proto_snap_v1_snap_proto_depIdxs = []int32{
	0, // 0: anapaya.snap.v1.SnapControl.GetSnapDataPlaneAddress:input_type -> anapaya.snap.v1.GetSnapDataPlaneRequest
	2, // 1: anapaya.snap.v1.SnapControl.RegisterSnapTunIdentity:input_type -> anapaya.snap.v1.RegisterSnapTunIdentityRequest
	1, // 2: anapaya.snap.v1.SnapControl.GetSnapDataPlaneAddress:output_type -> anapaya.snap.v1.GetSnapDataPlaneResponse
	3, // 3: anapaya.snap.v1.SnapControl.RegisterSnapTunIdentity:output_type -> anapaya.snap.v1.RegisterSnapTunIdentityResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_snap_v1_snap_proto_init() }
func file_proto_snap_v1_snap_proto_init() {
	if File_proto_snap_v1_snap_proto != nil {
		return
	}
	file_proto_snap_v1_snap_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_snap_v1_snap_proto_rawDesc), len(file_proto_snap_v1_snap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_snap_v1_snap_proto_goTypes,
		DependencyIndexes: file_proto_snap_v1_snap_proto_depIdxs,
		MessageInfos:      file_proto_snap_v1_snap_proto_msgTypes,
	}.Build()
	File_proto_snap_v1_snap_proto = out.File
	file_proto_snap_v1_snap_proto_goTypes = nil
	file_proto_snap_v1_snap_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SnapControlClient is the client API for SnapControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnapControlClient interface {
	GetSnapDataPlaneAddress(ctx context.Context, in *GetSnapDataPlaneRequest, opts ...grpc.CallOption) (*GetSnapDataPlaneResponse, error)
	RegisterSnapTunIdentity(ctx context.Context, in *RegisterSnapTunIdentityRequest, opts ...grpc.CallOption) (*RegisterSnapTunIdentityResponse, error)
}

type snapControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapControlClient(cc grpc.ClientConnInterface) SnapControlClient {
	return &snapControlClient{cc}
}

func (c *snapControlClient) GetSnapDataPlaneAddress(ctx context.Context, in *GetSnapDataPlaneRequest, opts ...grpc.CallOption) (*GetSnapDataPlaneResponse, error) {
	out := new(GetSnapDataPlaneResponse)
	err := c.cc.Invoke(ctx, "/anapaya.snap.v1.SnapControl/GetSnapDataPlaneAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapControlClient) RegisterSnapTunIdentity(ctx context.Context, in *RegisterSnapTunIdentityRequest, opts ...grpc.CallOption) (*RegisterSnapTunIdentityResponse, error) {
	out := new(RegisterSnapTunIdentityResponse)
	err := c.cc.Invoke(ctx, "/anapaya.snap.v1.SnapControl/RegisterSnapTunIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapControlServer is the server API for SnapControl service.
type SnapControlServer interface {
	GetSnapDataPlaneAddress(context.Context, *GetSnapDataPlaneRequest) (*GetSnapDataPlaneResponse, error)
	RegisterSnapTunIdentity(context.Context, *RegisterSnapTunIdentityRequest) (*RegisterSnapTunIdentityResponse, error)
}

// UnimplementedSnapControlServer can be embedded to have forward compatible implementations.
type UnimplementedSnapControlServer struct {
}

func (*UnimplementedSnapControlServer) GetSnapDataPlaneAddress(context.Context, *GetSnapDataPlaneRequest) (*GetSnapDataPlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapDataPlaneAddress not implemented")
}
func (*UnimplementedSnapControlServer) RegisterSnapTunIdentity(context.Context, *RegisterSnapTunIdentityRequest) (*RegisterSnapTunIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSnapTunIdentity not implemented")
}

func RegisterSnapControlServer(s *grpc.Server, srv SnapControlServer) {
	s.RegisterService(&_SnapControl_serviceDesc, srv)
}

func _SnapControl_GetSnapDataPlaneAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapDataPlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapControlServer).GetSnapDataPlaneAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anapaya.snap.v1.SnapControl/GetSnapDataPlaneAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapControlServer).GetSnapDataPlaneAddress(ctx, req.(*GetSnapDataPlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapControl_RegisterSnapTunIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSnapTunIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapControlServer).RegisterSnapTunIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anapaya.snap.v1.SnapControl/RegisterSnapTunIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapControlServer).RegisterSnapTunIdentity(ctx, req.(*RegisterSnapTunIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SnapControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "anapaya.snap.v1.SnapControl",
	HandlerType: (*SnapControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapDataPlaneAddress",
			Handler:    _SnapControl_GetSnapDataPlaneAddress_Handler,
		},
		{
			MethodName: "RegisterSnapTunIdentity",
			Handler:    _SnapControl_RegisterSnapTunIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/snap/v1/snap.proto",
}
