load("@rules_go//go:def.bzl", "go_library")
load("//tools:go.bzl", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["hummingbird.go"],
    importpath = "github.com/scionproto/scion/pkg/hummingbird",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/addr:go_default_library",
        "//pkg/slayers/path/hummingbird:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["hummingbird_test.go"],
    embed = [":go_default_library"],
    deps = ["@com_github_stretchr_testify//require:go_default_library"],
)
