// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.10
// source: proto/control_plane/experimental/v1/fabrid.proto

package experimental

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MPLSIPArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry []*MPLSIP `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
}

func (x *MPLSIPArray) Reset() {
	*x = MPLSIPArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPLSIPArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPLSIPArray) ProtoMessage() {}

func (x *MPLSIPArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPLSIPArray.ProtoReflect.Descriptor instead.
func (*MPLSIPArray) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{0}
}

func (x *MPLSIPArray) GetEntry() []*MPLSIP {
	if x != nil {
		return x.Entry
	}
	return nil
}

type MPLSIP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MplsLabel uint32 `protobuf:"varint,1,opt,name=mpls_label,json=mplsLabel,proto3" json:"mpls_label,omitempty"`
	Ip        []byte `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Prefix    uint32 `protobuf:"varint,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *MPLSIP) Reset() {
	*x = MPLSIP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPLSIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPLSIP) ProtoMessage() {}

func (x *MPLSIP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPLSIP.ProtoReflect.Descriptor instead.
func (*MPLSIP) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{1}
}

func (x *MPLSIP) GetMplsLabel() uint32 {
	if x != nil {
		return x.MplsLabel
	}
	return 0
}

func (x *MPLSIP) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *MPLSIP) GetPrefix() uint32 {
	if x != nil {
		return x.Prefix
	}
	return 0
}

type MPLSMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *MPLSMapRequest) Reset() {
	*x = MPLSMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPLSMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPLSMapRequest) ProtoMessage() {}

func (x *MPLSMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPLSMapRequest.ProtoReflect.Descriptor instead.
func (*MPLSMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{2}
}

func (x *MPLSMapRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type MPLSMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Update                   bool                    `protobuf:"varint,1,opt,name=update,proto3" json:"update,omitempty"`
	Hash                     []byte                  `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	MplsInterfacePoliciesMap map[uint64]uint32       `protobuf:"bytes,3,rep,name=mpls_interface_policies_map,json=mplsInterfacePoliciesMap,proto3" json:"mpls_interface_policies_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	MplsIpMap                map[uint32]*MPLSIPArray `protobuf:"bytes,4,rep,name=mpls_ip_map,json=mplsIpMap,proto3" json:"mpls_ip_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MPLSMapResponse) Reset() {
	*x = MPLSMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPLSMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPLSMapResponse) ProtoMessage() {}

func (x *MPLSMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPLSMapResponse.ProtoReflect.Descriptor instead.
func (*MPLSMapResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{3}
}

func (x *MPLSMapResponse) GetUpdate() bool {
	if x != nil {
		return x.Update
	}
	return false
}

func (x *MPLSMapResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *MPLSMapResponse) GetMplsInterfacePoliciesMap() map[uint64]uint32 {
	if x != nil {
		return x.MplsInterfacePoliciesMap
	}
	return nil
}

func (x *MPLSMapResponse) GetMplsIpMap() map[uint32]*MPLSIPArray {
	if x != nil {
		return x.MplsIpMap
	}
	return nil
}

type SupportedIndicesMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SupportedIndicesMapRequest) Reset() {
	*x = SupportedIndicesMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedIndicesMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedIndicesMapRequest) ProtoMessage() {}

func (x *SupportedIndicesMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedIndicesMapRequest.ProtoReflect.Descriptor instead.
func (*SupportedIndicesMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{4}
}

type SupportedIndicesMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportedIndicesMap []*FABRIDIndexMapEntry `protobuf:"bytes,1,rep,name=supported_indices_map,json=supportedIndicesMap,proto3" json:"supported_indices_map,omitempty"`
}

func (x *SupportedIndicesMapResponse) Reset() {
	*x = SupportedIndicesMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedIndicesMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedIndicesMapResponse) ProtoMessage() {}

func (x *SupportedIndicesMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedIndicesMapResponse.ProtoReflect.Descriptor instead.
func (*SupportedIndicesMapResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{5}
}

func (x *SupportedIndicesMapResponse) GetSupportedIndicesMap() []*FABRIDIndexMapEntry {
	if x != nil {
		return x.SupportedIndicesMap
	}
	return nil
}

type IndexIdentifierMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IndexIdentifierMapRequest) Reset() {
	*x = IndexIdentifierMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexIdentifierMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexIdentifierMapRequest) ProtoMessage() {}

func (x *IndexIdentifierMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexIdentifierMapRequest.ProtoReflect.Descriptor instead.
func (*IndexIdentifierMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{6}
}

type IndexIdentifierMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexIdentifierMap map[uint32]*FABRIDPolicyIdentifier `protobuf:"bytes,1,rep,name=index_identifier_map,json=indexIdentifierMap,proto3" json:"index_identifier_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *IndexIdentifierMapResponse) Reset() {
	*x = IndexIdentifierMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexIdentifierMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexIdentifierMapResponse) ProtoMessage() {}

func (x *IndexIdentifierMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexIdentifierMapResponse.ProtoReflect.Descriptor instead.
func (*IndexIdentifierMapResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{7}
}

func (x *IndexIdentifierMapResponse) GetIndexIdentifierMap() map[uint32]*FABRIDPolicyIdentifier {
	if x != nil {
		return x.IndexIdentifierMap
	}
	return nil
}

type RemotePolicyDescriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyIdentifier uint32 `protobuf:"varint,1,opt,name=policy_identifier,json=policyIdentifier,proto3" json:"policy_identifier,omitempty"`
	IsdAs            uint64 `protobuf:"varint,2,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
}

func (x *RemotePolicyDescriptionRequest) Reset() {
	*x = RemotePolicyDescriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemotePolicyDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePolicyDescriptionRequest) ProtoMessage() {}

func (x *RemotePolicyDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePolicyDescriptionRequest.ProtoReflect.Descriptor instead.
func (*RemotePolicyDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{8}
}

func (x *RemotePolicyDescriptionRequest) GetPolicyIdentifier() uint32 {
	if x != nil {
		return x.PolicyIdentifier
	}
	return 0
}

func (x *RemotePolicyDescriptionRequest) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

type RemotePolicyDescriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *RemotePolicyDescriptionResponse) Reset() {
	*x = RemotePolicyDescriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemotePolicyDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePolicyDescriptionResponse) ProtoMessage() {}

func (x *RemotePolicyDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePolicyDescriptionResponse.ProtoReflect.Descriptor instead.
func (*RemotePolicyDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{9}
}

func (x *RemotePolicyDescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type LocalPolicyDescriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyIdentifier uint32 `protobuf:"varint,1,opt,name=policy_identifier,json=policyIdentifier,proto3" json:"policy_identifier,omitempty"`
}

func (x *LocalPolicyDescriptionRequest) Reset() {
	*x = LocalPolicyDescriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalPolicyDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalPolicyDescriptionRequest) ProtoMessage() {}

func (x *LocalPolicyDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalPolicyDescriptionRequest.ProtoReflect.Descriptor instead.
func (*LocalPolicyDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{10}
}

func (x *LocalPolicyDescriptionRequest) GetPolicyIdentifier() uint32 {
	if x != nil {
		return x.PolicyIdentifier
	}
	return 0
}

type LocalPolicyDescriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *LocalPolicyDescriptionResponse) Reset() {
	*x = LocalPolicyDescriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalPolicyDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalPolicyDescriptionResponse) ProtoMessage() {}

func (x *LocalPolicyDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalPolicyDescriptionResponse.ProtoReflect.Descriptor instead.
func (*LocalPolicyDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{11}
}

func (x *LocalPolicyDescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RemoteMapsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Digest []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	IsdAs  uint64 `protobuf:"varint,2,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
}

func (x *RemoteMapsRequest) Reset() {
	*x = RemoteMapsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteMapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMapsRequest) ProtoMessage() {}

func (x *RemoteMapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMapsRequest.ProtoReflect.Descriptor instead.
func (*RemoteMapsRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{12}
}

func (x *RemoteMapsRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *RemoteMapsRequest) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

type RemoteMapsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maps *FABRIDDetachableMaps `protobuf:"bytes,1,opt,name=maps,proto3" json:"maps,omitempty"`
}

func (x *RemoteMapsResponse) Reset() {
	*x = RemoteMapsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteMapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMapsResponse) ProtoMessage() {}

func (x *RemoteMapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMapsResponse.ProtoReflect.Descriptor instead.
func (*RemoteMapsResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{13}
}

func (x *RemoteMapsResponse) GetMaps() *FABRIDDetachableMaps {
	if x != nil {
		return x.Maps
	}
	return nil
}

type DetachedMapsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DetachedMapsRequest) Reset() {
	*x = DetachedMapsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachedMapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachedMapsRequest) ProtoMessage() {}

func (x *DetachedMapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachedMapsRequest.ProtoReflect.Descriptor instead.
func (*DetachedMapsRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{14}
}

type DetachedMapsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maps *FABRIDDetachableMaps `protobuf:"bytes,1,opt,name=maps,proto3" json:"maps,omitempty"`
}

func (x *DetachedMapsResponse) Reset() {
	*x = DetachedMapsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachedMapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachedMapsResponse) ProtoMessage() {}

func (x *DetachedMapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachedMapsResponse.ProtoReflect.Descriptor instead.
func (*DetachedMapsResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP(), []int{15}
}

func (x *DetachedMapsResponse) GetMaps() *FABRIDDetachableMaps {
	if x != nil {
		return x.Maps
	}
	return nil
}

var File_proto_control_plane_experimental_v1_fabrid_proto protoreflect.FileDescriptor

var file_proto_control_plane_experimental_v1_fabrid_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x64, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0b, 0x4d, 0x50, 0x4c, 0x53, 0x49, 0x50, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x12, 0x41, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x50, 0x4c, 0x53, 0x49, 0x50, 0x52,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x4f, 0x0a, 0x06, 0x4d, 0x50, 0x4c, 0x53, 0x49, 0x50,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x70, 0x6c, 0x73, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x70, 0x6c, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0x24, 0x0a, 0x0e, 0x4d, 0x50, 0x4c, 0x53, 0x4d,
	0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0xf3, 0x03,
	0x0a, 0x0f, 0x4d, 0x50, 0x4c, 0x53, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x91, 0x01,
	0x0a, 0x1b, 0x6d, 0x70, 0x6c, 0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x52, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x50, 0x4c, 0x53, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x70, 0x6c, 0x73, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x18, 0x6d, 0x70, 0x6c, 0x73, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x4d, 0x61,
	0x70, 0x12, 0x63, 0x0a, 0x0b, 0x6d, 0x70, 0x6c, 0x73, 0x5f, 0x69, 0x70, 0x5f, 0x6d, 0x61, 0x70,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x50, 0x4c,
	0x53, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x70, 0x6c,
	0x73, 0x49, 0x70, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6d, 0x70, 0x6c,
	0x73, 0x49, 0x70, 0x4d, 0x61, 0x70, 0x1a, 0x4b, 0x0a, 0x1d, 0x4d, 0x70, 0x6c, 0x73, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x6e, 0x0a, 0x0e, 0x4d, 0x70, 0x6c, 0x73, 0x49, 0x70, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x46, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x50, 0x4c,
	0x53, 0x49, 0x50, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x1c, 0x0a, 0x1a, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x8b, 0x01, 0x0a, 0x1b, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6c, 0x0a, 0x15, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x69,
	0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x41, 0x42, 0x52, 0x49, 0x44, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x13, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x22,
	0x1b, 0x0a, 0x19, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xad, 0x02, 0x0a,
	0x1a, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x89, 0x01, 0x0a, 0x14,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x57, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x12, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x1a, 0x82, 0x01, 0x0a, 0x17, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x51, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x41, 0x42, 0x52, 0x49,
	0x44, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x64, 0x0a, 0x1e,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b,
	0x0a, 0x11, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x69,
	0x73, 0x64, 0x5f, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x73, 0x64,
	0x41, 0x73, 0x22, 0x43, 0x0a, 0x1f, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4c, 0x0a, 0x1d, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x10, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x1e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x11, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x64, 0x5f, 0x61, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x73, 0x64, 0x41, 0x73, 0x22, 0x63, 0x0a,
	0x12, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x39, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x41, 0x42, 0x52, 0x49, 0x44, 0x44, 0x65,
	0x74, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x04, 0x6d, 0x61,
	0x70, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4d, 0x61,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x65, 0x0a, 0x14, 0x44, 0x65, 0x74,
	0x61, 0x63, 0x68, 0x65, 0x64, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4d, 0x0a, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x39, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x41, 0x42, 0x52, 0x49, 0x44, 0x44, 0x65, 0x74, 0x61,
	0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x04, 0x6d, 0x61, 0x70, 0x73,
	0x32, 0xf9, 0x04, 0x0a, 0x12, 0x46, 0x41, 0x42, 0x52, 0x49, 0x44, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x9a, 0x01, 0x0a, 0x13, 0x53, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x12,
	0x3f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x40, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x97, 0x01, 0x0a, 0x12, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x12, 0x3e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x85,
	0x01, 0x0a, 0x0c, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4d, 0x61, 0x70, 0x73, 0x12,
	0x38, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4d, 0x61,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0xa3, 0x01, 0x0a, 0x16, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x42, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xb6, 0x03, 0x0a,
	0x12, 0x46, 0x41, 0x42, 0x52, 0x49, 0x44, 0x49, 0x6e, 0x74, 0x72, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0xa6, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7f, 0x0a, 0x0a,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x73, 0x12, 0x36, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4d,
	0x61, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a,
	0x07, 0x4d, 0x50, 0x4c, 0x53, 0x4d, 0x61, 0x70, 0x12, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x50, 0x4c, 0x53, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x50, 0x4c, 0x53, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x63, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_control_plane_experimental_v1_fabrid_proto_rawDescOnce sync.Once
	file_proto_control_plane_experimental_v1_fabrid_proto_rawDescData = file_proto_control_plane_experimental_v1_fabrid_proto_rawDesc
)

func file_proto_control_plane_experimental_v1_fabrid_proto_rawDescGZIP() []byte {
	file_proto_control_plane_experimental_v1_fabrid_proto_rawDescOnce.Do(func() {
		file_proto_control_plane_experimental_v1_fabrid_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_control_plane_experimental_v1_fabrid_proto_rawDescData)
	})
	return file_proto_control_plane_experimental_v1_fabrid_proto_rawDescData
}

var file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_control_plane_experimental_v1_fabrid_proto_goTypes = []interface{}{
	(*MPLSIPArray)(nil),                     // 0: proto.control_plane.experimental.v1.MPLSIPArray
	(*MPLSIP)(nil),                          // 1: proto.control_plane.experimental.v1.MPLSIP
	(*MPLSMapRequest)(nil),                  // 2: proto.control_plane.experimental.v1.MPLSMapRequest
	(*MPLSMapResponse)(nil),                 // 3: proto.control_plane.experimental.v1.MPLSMapResponse
	(*SupportedIndicesMapRequest)(nil),      // 4: proto.control_plane.experimental.v1.SupportedIndicesMapRequest
	(*SupportedIndicesMapResponse)(nil),     // 5: proto.control_plane.experimental.v1.SupportedIndicesMapResponse
	(*IndexIdentifierMapRequest)(nil),       // 6: proto.control_plane.experimental.v1.IndexIdentifierMapRequest
	(*IndexIdentifierMapResponse)(nil),      // 7: proto.control_plane.experimental.v1.IndexIdentifierMapResponse
	(*RemotePolicyDescriptionRequest)(nil),  // 8: proto.control_plane.experimental.v1.RemotePolicyDescriptionRequest
	(*RemotePolicyDescriptionResponse)(nil), // 9: proto.control_plane.experimental.v1.RemotePolicyDescriptionResponse
	(*LocalPolicyDescriptionRequest)(nil),   // 10: proto.control_plane.experimental.v1.LocalPolicyDescriptionRequest
	(*LocalPolicyDescriptionResponse)(nil),  // 11: proto.control_plane.experimental.v1.LocalPolicyDescriptionResponse
	(*RemoteMapsRequest)(nil),               // 12: proto.control_plane.experimental.v1.RemoteMapsRequest
	(*RemoteMapsResponse)(nil),              // 13: proto.control_plane.experimental.v1.RemoteMapsResponse
	(*DetachedMapsRequest)(nil),             // 14: proto.control_plane.experimental.v1.DetachedMapsRequest
	(*DetachedMapsResponse)(nil),            // 15: proto.control_plane.experimental.v1.DetachedMapsResponse
	nil,                                     // 16: proto.control_plane.experimental.v1.MPLSMapResponse.MplsInterfacePoliciesMapEntry
	nil,                                     // 17: proto.control_plane.experimental.v1.MPLSMapResponse.MplsIpMapEntry
	nil,                                     // 18: proto.control_plane.experimental.v1.IndexIdentifierMapResponse.IndexIdentifierMapEntry
	(*FABRIDIndexMapEntry)(nil),             // 19: proto.control_plane.experimental.v1.FABRIDIndexMapEntry
	(*FABRIDDetachableMaps)(nil),            // 20: proto.control_plane.experimental.v1.FABRIDDetachableMaps
	(*FABRIDPolicyIdentifier)(nil),          // 21: proto.control_plane.experimental.v1.FABRIDPolicyIdentifier
}
var file_proto_control_plane_experimental_v1_fabrid_proto_depIdxs = []int32{
	1,  // 0: proto.control_plane.experimental.v1.MPLSIPArray.entry:type_name -> proto.control_plane.experimental.v1.MPLSIP
	16, // 1: proto.control_plane.experimental.v1.MPLSMapResponse.mpls_interface_policies_map:type_name -> proto.control_plane.experimental.v1.MPLSMapResponse.MplsInterfacePoliciesMapEntry
	17, // 2: proto.control_plane.experimental.v1.MPLSMapResponse.mpls_ip_map:type_name -> proto.control_plane.experimental.v1.MPLSMapResponse.MplsIpMapEntry
	19, // 3: proto.control_plane.experimental.v1.SupportedIndicesMapResponse.supported_indices_map:type_name -> proto.control_plane.experimental.v1.FABRIDIndexMapEntry
	18, // 4: proto.control_plane.experimental.v1.IndexIdentifierMapResponse.index_identifier_map:type_name -> proto.control_plane.experimental.v1.IndexIdentifierMapResponse.IndexIdentifierMapEntry
	20, // 5: proto.control_plane.experimental.v1.RemoteMapsResponse.maps:type_name -> proto.control_plane.experimental.v1.FABRIDDetachableMaps
	20, // 6: proto.control_plane.experimental.v1.DetachedMapsResponse.maps:type_name -> proto.control_plane.experimental.v1.FABRIDDetachableMaps
	0,  // 7: proto.control_plane.experimental.v1.MPLSMapResponse.MplsIpMapEntry.value:type_name -> proto.control_plane.experimental.v1.MPLSIPArray
	21, // 8: proto.control_plane.experimental.v1.IndexIdentifierMapResponse.IndexIdentifierMapEntry.value:type_name -> proto.control_plane.experimental.v1.FABRIDPolicyIdentifier
	4,  // 9: proto.control_plane.experimental.v1.FABRIDInterService.SupportedIndicesMap:input_type -> proto.control_plane.experimental.v1.SupportedIndicesMapRequest
	6,  // 10: proto.control_plane.experimental.v1.FABRIDInterService.IndexIdentifierMap:input_type -> proto.control_plane.experimental.v1.IndexIdentifierMapRequest
	14, // 11: proto.control_plane.experimental.v1.FABRIDInterService.DetachedMaps:input_type -> proto.control_plane.experimental.v1.DetachedMapsRequest
	10, // 12: proto.control_plane.experimental.v1.FABRIDInterService.LocalPolicyDescription:input_type -> proto.control_plane.experimental.v1.LocalPolicyDescriptionRequest
	8,  // 13: proto.control_plane.experimental.v1.FABRIDIntraService.RemotePolicyDescription:input_type -> proto.control_plane.experimental.v1.RemotePolicyDescriptionRequest
	12, // 14: proto.control_plane.experimental.v1.FABRIDIntraService.RemoteMaps:input_type -> proto.control_plane.experimental.v1.RemoteMapsRequest
	2,  // 15: proto.control_plane.experimental.v1.FABRIDIntraService.MPLSMap:input_type -> proto.control_plane.experimental.v1.MPLSMapRequest
	5,  // 16: proto.control_plane.experimental.v1.FABRIDInterService.SupportedIndicesMap:output_type -> proto.control_plane.experimental.v1.SupportedIndicesMapResponse
	7,  // 17: proto.control_plane.experimental.v1.FABRIDInterService.IndexIdentifierMap:output_type -> proto.control_plane.experimental.v1.IndexIdentifierMapResponse
	15, // 18: proto.control_plane.experimental.v1.FABRIDInterService.DetachedMaps:output_type -> proto.control_plane.experimental.v1.DetachedMapsResponse
	11, // 19: proto.control_plane.experimental.v1.FABRIDInterService.LocalPolicyDescription:output_type -> proto.control_plane.experimental.v1.LocalPolicyDescriptionResponse
	9,  // 20: proto.control_plane.experimental.v1.FABRIDIntraService.RemotePolicyDescription:output_type -> proto.control_plane.experimental.v1.RemotePolicyDescriptionResponse
	13, // 21: proto.control_plane.experimental.v1.FABRIDIntraService.RemoteMaps:output_type -> proto.control_plane.experimental.v1.RemoteMapsResponse
	3,  // 22: proto.control_plane.experimental.v1.FABRIDIntraService.MPLSMap:output_type -> proto.control_plane.experimental.v1.MPLSMapResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_control_plane_experimental_v1_fabrid_proto_init() }
func file_proto_control_plane_experimental_v1_fabrid_proto_init() {
	if File_proto_control_plane_experimental_v1_fabrid_proto != nil {
		return
	}
	file_proto_control_plane_experimental_v1_fabrid_extensions_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPLSIPArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPLSIP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPLSMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPLSMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedIndicesMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedIndicesMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexIdentifierMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexIdentifierMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemotePolicyDescriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemotePolicyDescriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalPolicyDescriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalPolicyDescriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteMapsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteMapsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachedMapsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachedMapsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_control_plane_experimental_v1_fabrid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_control_plane_experimental_v1_fabrid_proto_goTypes,
		DependencyIndexes: file_proto_control_plane_experimental_v1_fabrid_proto_depIdxs,
		MessageInfos:      file_proto_control_plane_experimental_v1_fabrid_proto_msgTypes,
	}.Build()
	File_proto_control_plane_experimental_v1_fabrid_proto = out.File
	file_proto_control_plane_experimental_v1_fabrid_proto_rawDesc = nil
	file_proto_control_plane_experimental_v1_fabrid_proto_goTypes = nil
	file_proto_control_plane_experimental_v1_fabrid_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FABRIDInterServiceClient is the client API for FABRIDInterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FABRIDInterServiceClient interface {
	SupportedIndicesMap(ctx context.Context, in *SupportedIndicesMapRequest, opts ...grpc.CallOption) (*SupportedIndicesMapResponse, error)
	IndexIdentifierMap(ctx context.Context, in *IndexIdentifierMapRequest, opts ...grpc.CallOption) (*IndexIdentifierMapResponse, error)
	DetachedMaps(ctx context.Context, in *DetachedMapsRequest, opts ...grpc.CallOption) (*DetachedMapsResponse, error)
	LocalPolicyDescription(ctx context.Context, in *LocalPolicyDescriptionRequest, opts ...grpc.CallOption) (*LocalPolicyDescriptionResponse, error)
}

type fABRIDInterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFABRIDInterServiceClient(cc grpc.ClientConnInterface) FABRIDInterServiceClient {
	return &fABRIDInterServiceClient{cc}
}

func (c *fABRIDInterServiceClient) SupportedIndicesMap(ctx context.Context, in *SupportedIndicesMapRequest, opts ...grpc.CallOption) (*SupportedIndicesMapResponse, error) {
	out := new(SupportedIndicesMapResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.experimental.v1.FABRIDInterService/SupportedIndicesMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fABRIDInterServiceClient) IndexIdentifierMap(ctx context.Context, in *IndexIdentifierMapRequest, opts ...grpc.CallOption) (*IndexIdentifierMapResponse, error) {
	out := new(IndexIdentifierMapResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.experimental.v1.FABRIDInterService/IndexIdentifierMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fABRIDInterServiceClient) DetachedMaps(ctx context.Context, in *DetachedMapsRequest, opts ...grpc.CallOption) (*DetachedMapsResponse, error) {
	out := new(DetachedMapsResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.experimental.v1.FABRIDInterService/DetachedMaps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fABRIDInterServiceClient) LocalPolicyDescription(ctx context.Context, in *LocalPolicyDescriptionRequest, opts ...grpc.CallOption) (*LocalPolicyDescriptionResponse, error) {
	out := new(LocalPolicyDescriptionResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.experimental.v1.FABRIDInterService/LocalPolicyDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FABRIDInterServiceServer is the server API for FABRIDInterService service.
type FABRIDInterServiceServer interface {
	SupportedIndicesMap(context.Context, *SupportedIndicesMapRequest) (*SupportedIndicesMapResponse, error)
	IndexIdentifierMap(context.Context, *IndexIdentifierMapRequest) (*IndexIdentifierMapResponse, error)
	DetachedMaps(context.Context, *DetachedMapsRequest) (*DetachedMapsResponse, error)
	LocalPolicyDescription(context.Context, *LocalPolicyDescriptionRequest) (*LocalPolicyDescriptionResponse, error)
}

// UnimplementedFABRIDInterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFABRIDInterServiceServer struct {
}

func (*UnimplementedFABRIDInterServiceServer) SupportedIndicesMap(context.Context, *SupportedIndicesMapRequest) (*SupportedIndicesMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupportedIndicesMap not implemented")
}
func (*UnimplementedFABRIDInterServiceServer) IndexIdentifierMap(context.Context, *IndexIdentifierMapRequest) (*IndexIdentifierMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexIdentifierMap not implemented")
}
func (*UnimplementedFABRIDInterServiceServer) DetachedMaps(context.Context, *DetachedMapsRequest) (*DetachedMapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetachedMaps not implemented")
}
func (*UnimplementedFABRIDInterServiceServer) LocalPolicyDescription(context.Context, *LocalPolicyDescriptionRequest) (*LocalPolicyDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalPolicyDescription not implemented")
}

func RegisterFABRIDInterServiceServer(s *grpc.Server, srv FABRIDInterServiceServer) {
	s.RegisterService(&_FABRIDInterService_serviceDesc, srv)
}

func _FABRIDInterService_SupportedIndicesMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportedIndicesMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FABRIDInterServiceServer).SupportedIndicesMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.experimental.v1.FABRIDInterService/SupportedIndicesMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FABRIDInterServiceServer).SupportedIndicesMap(ctx, req.(*SupportedIndicesMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FABRIDInterService_IndexIdentifierMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexIdentifierMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FABRIDInterServiceServer).IndexIdentifierMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.experimental.v1.FABRIDInterService/IndexIdentifierMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FABRIDInterServiceServer).IndexIdentifierMap(ctx, req.(*IndexIdentifierMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FABRIDInterService_DetachedMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachedMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FABRIDInterServiceServer).DetachedMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.experimental.v1.FABRIDInterService/DetachedMaps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FABRIDInterServiceServer).DetachedMaps(ctx, req.(*DetachedMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FABRIDInterService_LocalPolicyDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalPolicyDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FABRIDInterServiceServer).LocalPolicyDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.experimental.v1.FABRIDInterService/LocalPolicyDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FABRIDInterServiceServer).LocalPolicyDescription(ctx, req.(*LocalPolicyDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FABRIDInterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.control_plane.experimental.v1.FABRIDInterService",
	HandlerType: (*FABRIDInterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SupportedIndicesMap",
			Handler:    _FABRIDInterService_SupportedIndicesMap_Handler,
		},
		{
			MethodName: "IndexIdentifierMap",
			Handler:    _FABRIDInterService_IndexIdentifierMap_Handler,
		},
		{
			MethodName: "DetachedMaps",
			Handler:    _FABRIDInterService_DetachedMaps_Handler,
		},
		{
			MethodName: "LocalPolicyDescription",
			Handler:    _FABRIDInterService_LocalPolicyDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control_plane/experimental/v1/fabrid.proto",
}

// FABRIDIntraServiceClient is the client API for FABRIDIntraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FABRIDIntraServiceClient interface {
	RemotePolicyDescription(ctx context.Context, in *RemotePolicyDescriptionRequest, opts ...grpc.CallOption) (*RemotePolicyDescriptionResponse, error)
	RemoteMaps(ctx context.Context, in *RemoteMapsRequest, opts ...grpc.CallOption) (*RemoteMapsResponse, error)
	MPLSMap(ctx context.Context, in *MPLSMapRequest, opts ...grpc.CallOption) (*MPLSMapResponse, error)
}

type fABRIDIntraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFABRIDIntraServiceClient(cc grpc.ClientConnInterface) FABRIDIntraServiceClient {
	return &fABRIDIntraServiceClient{cc}
}

func (c *fABRIDIntraServiceClient) RemotePolicyDescription(ctx context.Context, in *RemotePolicyDescriptionRequest, opts ...grpc.CallOption) (*RemotePolicyDescriptionResponse, error) {
	out := new(RemotePolicyDescriptionResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.experimental.v1.FABRIDIntraService/RemotePolicyDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fABRIDIntraServiceClient) RemoteMaps(ctx context.Context, in *RemoteMapsRequest, opts ...grpc.CallOption) (*RemoteMapsResponse, error) {
	out := new(RemoteMapsResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.experimental.v1.FABRIDIntraService/RemoteMaps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fABRIDIntraServiceClient) MPLSMap(ctx context.Context, in *MPLSMapRequest, opts ...grpc.CallOption) (*MPLSMapResponse, error) {
	out := new(MPLSMapResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.experimental.v1.FABRIDIntraService/MPLSMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FABRIDIntraServiceServer is the server API for FABRIDIntraService service.
type FABRIDIntraServiceServer interface {
	RemotePolicyDescription(context.Context, *RemotePolicyDescriptionRequest) (*RemotePolicyDescriptionResponse, error)
	RemoteMaps(context.Context, *RemoteMapsRequest) (*RemoteMapsResponse, error)
	MPLSMap(context.Context, *MPLSMapRequest) (*MPLSMapResponse, error)
}

// UnimplementedFABRIDIntraServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFABRIDIntraServiceServer struct {
}

func (*UnimplementedFABRIDIntraServiceServer) RemotePolicyDescription(context.Context, *RemotePolicyDescriptionRequest) (*RemotePolicyDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemotePolicyDescription not implemented")
}
func (*UnimplementedFABRIDIntraServiceServer) RemoteMaps(context.Context, *RemoteMapsRequest) (*RemoteMapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoteMaps not implemented")
}
func (*UnimplementedFABRIDIntraServiceServer) MPLSMap(context.Context, *MPLSMapRequest) (*MPLSMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MPLSMap not implemented")
}

func RegisterFABRIDIntraServiceServer(s *grpc.Server, srv FABRIDIntraServiceServer) {
	s.RegisterService(&_FABRIDIntraService_serviceDesc, srv)
}

func _FABRIDIntraService_RemotePolicyDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePolicyDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FABRIDIntraServiceServer).RemotePolicyDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.experimental.v1.FABRIDIntraService/RemotePolicyDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FABRIDIntraServiceServer).RemotePolicyDescription(ctx, req.(*RemotePolicyDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FABRIDIntraService_RemoteMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FABRIDIntraServiceServer).RemoteMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.experimental.v1.FABRIDIntraService/RemoteMaps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FABRIDIntraServiceServer).RemoteMaps(ctx, req.(*RemoteMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FABRIDIntraService_MPLSMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MPLSMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FABRIDIntraServiceServer).MPLSMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.experimental.v1.FABRIDIntraService/MPLSMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FABRIDIntraServiceServer).MPLSMap(ctx, req.(*MPLSMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FABRIDIntraService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.control_plane.experimental.v1.FABRIDIntraService",
	HandlerType: (*FABRIDIntraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemotePolicyDescription",
			Handler:    _FABRIDIntraService_RemotePolicyDescription_Handler,
		},
		{
			MethodName: "RemoteMaps",
			Handler:    _FABRIDIntraService_RemoteMaps_Handler,
		},
		{
			MethodName: "MPLSMap",
			Handler:    _FABRIDIntraService_MPLSMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control_plane/experimental/v1/fabrid.proto",
}
