load("//tools/lint:go.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["collector.go"],
    importpath = "github.com/scionproto/scion/collector",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/experimental/pot/monitor:go_default_library",
        "//pkg/grpc:go_default_library",
        "//pkg/log:go_default_library",
        "//pkg/proto/proof_of_forwarding:go_default_library",
        "//private/topology:go_default_library",
    ],
)
