// File generated by ANTLR. DO NOT EDIT.

package sequence

import (
	"fmt"
	"unicode"

	"github.com/antlr/antlr4/runtime/Go/antlr"
)

// Suppress unused import error
var _ = fmt.Printf
var _ = unicode.IsLetter

var serializedLexerAtn = []uint16{
	3, 24715, 42794, 33075, 47597, 16764, 15335, 30598, 22884, 2, 20, 104,
	8, 1, 4, 2, 9, 2, 4, 3, 9, 3, 4, 4, 9, 4, 4, 5, 9, 5, 4, 6, 9, 6, 4, 7,
	9, 7, 4, 8, 9, 8, 4, 9, 9, 9, 4, 10, 9, 10, 4, 11, 9, 11, 4, 12, 9, 12,
	4, 13, 9, 13, 4, 14, 9, 14, 4, 15, 9, 15, 4, 16, 9, 16, 4, 17, 9, 17, 4,
	18, 9, 18, 4, 19, 9, 19, 4, 20, 9, 20, 3, 2, 3, 2, 7, 2, 44, 10, 2, 12,
	2, 14, 2, 47, 11, 2, 3, 2, 5, 2, 50, 10, 2, 3, 3, 6, 3, 53, 10, 3, 13,
	3, 14, 3, 54, 3, 3, 3, 3, 3, 4, 3, 4, 3, 5, 3, 5, 7, 5, 63, 10, 5, 12,
	5, 14, 5, 66, 11, 5, 3, 6, 3, 6, 3, 6, 3, 7, 3, 7, 3, 7, 3, 8, 3, 8, 3,
	8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 9, 3, 9, 3, 10, 3, 10, 3, 11, 3, 11, 3, 12,
	3, 12, 3, 13, 3, 13, 3, 14, 3, 14, 3, 15, 3, 15, 3, 16, 3, 16, 3, 17, 3,
	17, 3, 18, 3, 18, 3, 19, 3, 19, 3, 20, 3, 20, 2, 2, 21, 3, 2, 5, 3, 7,
	4, 9, 5, 11, 6, 13, 7, 15, 8, 17, 9, 19, 10, 21, 11, 23, 12, 25, 13, 27,
	14, 29, 15, 31, 16, 33, 17, 35, 18, 37, 19, 39, 20, 3, 2, 7, 5, 2, 51,
	59, 67, 72, 99, 104, 5, 2, 50, 59, 67, 72, 99, 104, 5, 2, 11, 12, 15, 15,
	34, 34, 3, 2, 51, 59, 3, 2, 50, 59, 2, 106, 2, 5, 3, 2, 2, 2, 2, 7, 3,
	2, 2, 2, 2, 9, 3, 2, 2, 2, 2, 11, 3, 2, 2, 2, 2, 13, 3, 2, 2, 2, 2, 15,
	3, 2, 2, 2, 2, 17, 3, 2, 2, 2, 2, 19, 3, 2, 2, 2, 2, 21, 3, 2, 2, 2, 2,
	23, 3, 2, 2, 2, 2, 25, 3, 2, 2, 2, 2, 27, 3, 2, 2, 2, 2, 29, 3, 2, 2, 2,
	2, 31, 3, 2, 2, 2, 2, 33, 3, 2, 2, 2, 2, 35, 3, 2, 2, 2, 2, 37, 3, 2, 2,
	2, 2, 39, 3, 2, 2, 2, 3, 49, 3, 2, 2, 2, 5, 52, 3, 2, 2, 2, 7, 58, 3, 2,
	2, 2, 9, 60, 3, 2, 2, 2, 11, 67, 3, 2, 2, 2, 13, 70, 3, 2, 2, 2, 15, 73,
	3, 2, 2, 2, 17, 80, 3, 2, 2, 2, 19, 82, 3, 2, 2, 2, 21, 84, 3, 2, 2, 2,
	23, 86, 3, 2, 2, 2, 25, 88, 3, 2, 2, 2, 27, 90, 3, 2, 2, 2, 29, 92, 3,
	2, 2, 2, 31, 94, 3, 2, 2, 2, 33, 96, 3, 2, 2, 2, 35, 98, 3, 2, 2, 2, 37,
	100, 3, 2, 2, 2, 39, 102, 3, 2, 2, 2, 41, 45, 9, 2, 2, 2, 42, 44, 9, 3,
	2, 2, 43, 42, 3, 2, 2, 2, 44, 47, 3, 2, 2, 2, 45, 43, 3, 2, 2, 2, 45, 46,
	3, 2, 2, 2, 46, 50, 3, 2, 2, 2, 47, 45, 3, 2, 2, 2, 48, 50, 7, 50, 2, 2,
	49, 41, 3, 2, 2, 2, 49, 48, 3, 2, 2, 2, 50, 4, 3, 2, 2, 2, 51, 53, 9, 4,
	2, 2, 52, 51, 3, 2, 2, 2, 53, 54, 3, 2, 2, 2, 54, 52, 3, 2, 2, 2, 54, 55,
	3, 2, 2, 2, 55, 56, 3, 2, 2, 2, 56, 57, 8, 3, 2, 2, 57, 6, 3, 2, 2, 2,
	58, 59, 7, 50, 2, 2, 59, 8, 3, 2, 2, 2, 60, 64, 9, 5, 2, 2, 61, 63, 9,
	6, 2, 2, 62, 61, 3, 2, 2, 2, 63, 66, 3, 2, 2, 2, 64, 62, 3, 2, 2, 2, 64,
	65, 3, 2, 2, 2, 65, 10, 3, 2, 2, 2, 66, 64, 3, 2, 2, 2, 67, 68, 7, 47,
	2, 2, 68, 69, 7, 50, 2, 2, 69, 12, 3, 2, 2, 2, 70, 71, 7, 47, 2, 2, 71,
	72, 5, 9, 5, 2, 72, 14, 3, 2, 2, 2, 73, 74, 7, 47, 2, 2, 74, 75, 5, 3,
	2, 2, 75, 76, 7, 60, 2, 2, 76, 77, 5, 3, 2, 2, 77, 78, 7, 60, 2, 2, 78,
	79, 5, 3, 2, 2, 79, 16, 3, 2, 2, 2, 80, 81, 7, 37, 2, 2, 81, 18, 3, 2,
	2, 2, 82, 83, 7, 46, 2, 2, 83, 20, 3, 2, 2, 2, 84, 85, 7, 65, 2, 2, 85,
	22, 3, 2, 2, 2, 86, 87, 7, 45, 2, 2, 87, 24, 3, 2, 2, 2, 88, 89, 7, 44,
	2, 2, 89, 26, 3, 2, 2, 2, 90, 91, 7, 126, 2, 2, 91, 28, 3, 2, 2, 2, 92,
	93, 7, 42, 2, 2, 93, 30, 3, 2, 2, 2, 94, 95, 7, 43, 2, 2, 95, 32, 3, 2,
	2, 2, 96, 97, 7, 66, 2, 2, 97, 34, 3, 2, 2, 2, 98, 99, 7, 73, 2, 2, 99,
	36, 3, 2, 2, 2, 100, 101, 7, 78, 2, 2, 101, 38, 3, 2, 2, 2, 102, 103, 7,
	67, 2, 2, 103, 40, 3, 2, 2, 2, 7, 2, 45, 49, 54, 64, 3, 8, 2, 2,
}

var lexerChannelNames = []string{
	"DEFAULT_TOKEN_CHANNEL", "HIDDEN",
}

var lexerModeNames = []string{
	"DEFAULT_MODE",
}

var lexerLiteralNames = []string{
	"", "", "'0'", "", "", "", "", "'#'", "','", "'?'", "'+'", "'*'", "'|'",
	"'('", "')'", "'@'", "'G'", "'L'", "'A'",
}

var lexerSymbolicNames = []string{
	"", "WHITESPACE", "ZERO", "NUM", "WILDCARDAS", "LEGACYAS", "AS", "HASH",
	"COMMA", "QUESTIONMARK", "PLUS", "ASTERISK", "OR", "LPAR", "RPAR", "MONKEYTAIL",
	"GLOBALPOLICY", "LOCALPOLICY", "WILDCARDPOLICY",
}

var lexerRuleNames = []string{
	"HEXA", "WHITESPACE", "ZERO", "NUM", "WILDCARDAS", "LEGACYAS", "AS", "HASH",
	"COMMA", "QUESTIONMARK", "PLUS", "ASTERISK", "OR", "LPAR", "RPAR", "MONKEYTAIL",
	"GLOBALPOLICY", "LOCALPOLICY", "WILDCARDPOLICY",
}

type SequenceLexer struct {
	*antlr.BaseLexer
	channelNames []string
	modeNames    []string
	// TODO: EOF string
}

// NewSequenceLexer produces a new lexer instance for the optional input antlr.CharStream.
//
// The *SequenceLexer instance produced may be reused by calling the SetInputStream method.
// The initial lexer configuration is expensive to construct, and the object is not thread-safe;
// however, if used within a Golang sync.Pool, the construction cost amortizes well and the
// objects can be used in a thread-safe manner.
func NewSequenceLexer(input antlr.CharStream) *SequenceLexer {
	l := new(SequenceLexer)
	lexerDeserializer := antlr.NewATNDeserializer(nil)
	lexerAtn := lexerDeserializer.DeserializeFromUInt16(serializedLexerAtn)
	lexerDecisionToDFA := make([]*antlr.DFA, len(lexerAtn.DecisionToState))
	for index, ds := range lexerAtn.DecisionToState {
		lexerDecisionToDFA[index] = antlr.NewDFA(ds, index)
	}
	l.BaseLexer = antlr.NewBaseLexer(input)
	l.Interpreter = antlr.NewLexerATNSimulator(l, lexerAtn, lexerDecisionToDFA, antlr.NewPredictionContextCache())

	l.channelNames = lexerChannelNames
	l.modeNames = lexerModeNames
	l.RuleNames = lexerRuleNames
	l.LiteralNames = lexerLiteralNames
	l.SymbolicNames = lexerSymbolicNames
	l.GrammarFileName = "Sequence.g4"
	// TODO: l.EOF = antlr.TokenEOF

	return l
}

// SequenceLexer tokens.
const (
	SequenceLexerWHITESPACE     = 1
	SequenceLexerZERO           = 2
	SequenceLexerNUM            = 3
	SequenceLexerWILDCARDAS     = 4
	SequenceLexerLEGACYAS       = 5
	SequenceLexerAS             = 6
	SequenceLexerHASH           = 7
	SequenceLexerCOMMA          = 8
	SequenceLexerQUESTIONMARK   = 9
	SequenceLexerPLUS           = 10
	SequenceLexerASTERISK       = 11
	SequenceLexerOR             = 12
	SequenceLexerLPAR           = 13
	SequenceLexerRPAR           = 14
	SequenceLexerMONKEYTAIL     = 15
	SequenceLexerGLOBALPOLICY   = 16
	SequenceLexerLOCALPOLICY    = 17
	SequenceLexerWILDCARDPOLICY = 18
)
